const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../..');
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/\/$/,'/index.html'));if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',({'.css':'text/css','.js':'application/javascript','.html':'text/html','.json':'application/json','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.SAGS_BROWSER_EXECUTABLE?{executablePath:process.env.SAGS_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}:{channel:'chromium'})});
try{for(const width of [320,360,390,430,1280]){const page=await browser.newPage({viewport:{width,height:844},serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});await page.waitForTimeout(350);
 const login=page.locator('.roleLoginCard');await login.waitFor({state:'visible'});assert((await page.locator('#roleLoginSubmit').boundingBox()).height>=44);await page.locator('#personalLoginUser').fill('VISUAL_TEST');await page.locator('#roleLoginPass').fill('visual-only');assert.equal(await page.locator('#personalLoginUser').inputValue(),'VISUAL_TEST');
 if(width<768){assert.equal(await login.evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(6, 34, 64, 0.96)');const box=await login.boundingBox();assert(box.x>=0&&box.x+box.width<=width+1);}
 await page.evaluate(()=>{window.__sagsGetSession=()=>({role:'AD',profile:{username:'VISUAL_TEST',fullName:'Visual Test',role:'AD',active:true}});try{currentRole='AD';currentUserProfile={username:'VISUAL_TEST',fullName:'Visual Test',role:'AD',active:true}}catch{}document.getElementById('roleLoginModal').style.display='none';document.body.classList.add('v157-authenticated','v157-home');window.sagsV479GoHome();window.v157OpenMenu()});await page.waitForTimeout(180);
 if(width<768){const menu=page.locator('#v157Drawer'),box=await menu.boundingBox();assert(box&&box.x>=0&&box.x+box.width<=width+1);assert.equal(await menu.evaluate(e=>getComputedStyle(e).transform),'none');assert((await page.locator('#v157LogoutBtn').boundingBox()).height>=44);const labels=await page.locator('#v157Drawer .v157MenuItem .meta').evaluateAll(es=>es.filter(e=>getComputedStyle(e).display!=='none').length);assert.equal(labels,0);}
 await page.evaluate(()=>{document.getElementById('accountManagerModal').style.display='flex'});assert((await page.locator('#accountManagerModal .sagsAdminPanel').boundingBox()).width<=width);await page.evaluate(()=>{document.getElementById('accountManagerModal').style.display='none'});
 assert.deepEqual(errors,[]);await page.close();}
 console.log('Mobile UI: 320/360/390/430/1280px; login inputs, navy theme, menu, admin panel, touch targets, no JS errors passed.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
