const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'../..');
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/\/$/,'/index.html'));if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('Content-Type',({'.css':'text/css','.js':'application/javascript','.html':'text/html','.json':'application/json','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;try{browser=await chromium.launch({headless:true,...(process.env.SAGS_BROWSER_EXECUTABLE?{executablePath:process.env.SAGS_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}:{channel:'chromium'})});
for(const width of [360,375,390,412,430,1280]){const page=await browser.newPage({viewport:{width,height:width===320?640:844},serviceWorkers:'block'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'load'});await page.waitForFunction(()=>typeof window.v157OpenMenu==='function'&&typeof window.sagsV479GoHome==='function');
 const login=page.locator('.roleLoginCard');await login.waitFor({state:'visible'});assert((await page.locator('#roleLoginSubmit').boundingBox()).height>=44);await page.locator('#personalLoginUser').fill('VISUAL_TEST');await page.locator('#roleLoginPass').fill('visual-only');assert.equal(await page.locator('#personalLoginUser').inputValue(),'VISUAL_TEST');
 if(width<768){assert.equal(await login.evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(6, 34, 64, 0.96)');const box=await login.boundingBox();assert(box.x>=0&&box.x+box.width<=width+1);assert(box.height<=440,'login must leave room on mobile: '+box.height);if(process.env.SAGS_UI_SCREENSHOTS)await page.screenshot({path:path.join(process.env.SAGS_UI_SCREENSHOTS,'login-'+width+'.png')});}
 await page.waitForFunction(()=>!!window.__SAGS_POST_LOGIN_UNLOCK_V64123?.testTransition);await page.evaluate(()=>window.__SAGS_POST_LOGIN_UNLOCK_V64123.testTransition({username:'VISUAL_TEST',fullName:'Visual Test',name:'Visual Test',role:'AD',active:true,firebaseUid:'VISUAL_TEST_UID'}));await page.waitForFunction(()=>document.body.classList.contains('v157-authenticated')&&getComputedStyle(document.getElementById('roleLoginModal')).display==='none');assert.equal(await page.evaluate(()=>!!document.elementFromPoint(innerWidth/2,innerHeight/2)?.closest('#roleLoginModal')),false,'login overlay must not intercept the authenticated screen');await page.waitForTimeout(350);await page.evaluate(()=>window.v157OpenMenu());await page.locator('#v157Drawer .v157MenuItem').first().waitFor({state:'visible'});await page.waitForTimeout(180);
 if(width<768){const menu=page.locator('#v157Drawer'),box=await menu.boundingBox();assert(box&&box.x>=0&&box.x+box.width<=width+1,JSON.stringify({width,box,state:await page.evaluate(()=>({cls:document.body.className,transform:getComputedStyle(document.getElementById('v157Drawer')).transform,nav:getComputedStyle(document.getElementById('sagsNavigationHeader')).bottom}))}));assert(['none','matrix(1, 0, 0, 1, 0, 0)'].includes(await menu.evaluate(e=>getComputedStyle(e).transform)),'drawer must not be offset');assert((await page.locator('#v157LogoutBtn').boundingBox()).height>=44);const labels=await page.locator('#v157Drawer .v157MenuItem .meta').evaluateAll(es=>es.filter(e=>getComputedStyle(e).display!=='none').length);assert.equal(labels,0);
 const header=await page.locator('#sagsNavigationHeader').boundingBox();assert(header.height<=62,'bottom navigation must be compact');assert(header.y>=(width===320?640:844)-header.height-1,'navigation must stay at bottom');const pass=await page.locator('#v157PasswordBtn').boundingBox().catch(()=>null),logout=await page.locator('#v157LogoutBtn').boundingBox();assert(pass,'password button must be present');if(pass){assert(Math.abs(pass.y-logout.y)<2);assert(Math.abs(pass.width-logout.width)<2);}
 const cards=await page.locator('#v157Drawer .v157MenuItem').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height>0).map(e=>e.getBoundingClientRect().height));if(process.env.SAGS_UI_SCREENSHOTS)await page.screenshot({path:path.join(process.env.SAGS_UI_SCREENSHOTS,'menu-'+width+'.png')});assert(cards.length>0);assert(cards.every(h=>h<=56),'menu cards must be compact: '+cards);
 console.log('Compact '+width+'px: header '+header.height+'px; menu cards '+Math.max(...cards)+'px');
 if(process.env.SAGS_UI_SCREENSHOTS)await page.screenshot({path:path.join(process.env.SAGS_UI_SCREENSHOTS,'menu-'+width+'.png')});
 }
 if(width<768){
 await page.evaluate(()=>{window.__sagsGetSession=()=>({role:'DH',profile:{username:'VISUAL_TEST',role:'DH',active:true}});currentRole='DH';currentUserProfile={username:'VISUAL_TEST',role:'DH',active:true};window.sagsV478ManifestForWorker=async()=>({opDate:'2026-10-03',items:[]});const engine=window.__SAGS_DAILY_ROSTER_FINAL_V1199;engine.renderPersonal=async d=>{const item={flightName:'VU1270',depFlight:'VU1270',flightId:'visual',assignmentId:'visual-a',formGroup:'FSAGS423',route:'CXR-HAN',acReg:'VN-A123',sta:'10:00',std:'11:00'};document.getElementById('fwcList').innerHTML='<div class="v1199Tabs"><button class="v1199Tab">ĐANG LÀM</button><button class="v1199Tab">ĐÃ HOÀN TẤT</button></div>'+engine.cardHtml({key:'visual',primary:item,items:[item,{...item,assignmentId:'visual-b',formGroup:'FINAL'}],states:[{},{}],dossierDocs:[],flightClosed:false},d)};});
 await page.locator('[data-v157-key="myflight"]').click();await page.locator('#fwcModal .v1199FormTile').first().waitFor({state:'visible'});await page.waitForTimeout(250);
 const density=await page.locator('#fwcModal').evaluate(e=>({hero:e.querySelector('.fwcHead').getBoundingClientRect().height,form:e.querySelector('.v1199FormTile').getBoundingClientRect().height,flight:e.querySelector('.v1199Card').getBoundingClientRect().bottom,overflow:e.scrollWidth>innerWidth,date:e.querySelector('.sagsWorkDateControl').getBoundingClientRect().height}));
 assert(density.hero<=56,'real-route header must be compact');assert(density.form<=64,'canonical form tile must be compact');assert(density.date<=46,'wrapped date must be compact');assert(density.flight<=640,'first flight must fit');assert.equal(density.overflow,false);assert(await page.evaluate(()=>!!document.elementFromPoint(innerWidth/2,innerHeight-20)?.closest('#sagsNavigationHeader')),JSON.stringify(await page.evaluate(()=>{const n=document.getElementById('sagsNavigationHeader'),s=getComputedStyle(n);return {cls:document.body.className,style:n.getAttribute('style'),box:n.getBoundingClientRect().toJSON(),display:s.display,visibility:s.visibility,z:s.zIndex,point:document.elementFromPoint(innerWidth/2,innerHeight-20)?.outerHTML.slice(0,200)}})));assert.equal(await page.locator('#fwcModal button').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height>0&&/QUAY LẠI|TỰ NHẬN VIỆC/.test(e.textContent)).length),0);console.log('Real My Flight '+width+'px: header '+density.hero+'px, form '+density.form+'px');
 if(process.env.SAGS_UI_SCREENSHOTS)await page.screenshot({path:path.join(process.env.SAGS_UI_SCREENSHOTS,'myflight-'+width+'.png')});
 await page.locator('#sagsNavigationHeader #v163FlightBtn').click();assert(await page.evaluate(()=>document.body.classList.contains('v157-drawer-open')));assert(await page.locator('#v157Drawer').isVisible());await page.locator('#sagsNavigationHeader #v163FlightBtn').click();await page.evaluate(()=>window.flightWorkspaceClose());
 }
 await page.evaluate(()=>{document.getElementById('accountManagerModal').style.display='flex'});assert((await page.locator('#accountManagerModal .sagsAdminPanel').boundingBox()).width<=width);await page.evaluate(()=>{document.getElementById('accountManagerModal').style.display='none'});
 assert.deepEqual(errors,[]);await page.close();}
 console.log('Mobile UI: 360/375/390/412/430/1280px; login inputs, navy theme, menu, admin panel, touch targets, no JS errors passed.');
}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
