const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'app/boot/32-fixed-ui-rule-v64113.js'),'utf8');
const css=fs.readFileSync(path.join(root,'app/styles/fixed-ui-rule-v64113.css'),'utf8');
assert(js.includes("function isTechnicalFormHit(el){return !!el?.classList?.contains('sags5494DirectHit')}"),'fixed-ui must identify 54/94 technical hitboxes');
assert(js.includes("button:not(.sags5494DirectHit)"),'fixed-ui button scanner must exclude 54/94 hitboxes');
assert(js.includes("el.classList.remove('sagsUiButton','sagsAppButton')"),'fixed-ui must repair already-normalized 54/94 hitboxes');
assert(css.includes('FSAGS54/94 TECHNICAL HITBOX GUARD'),'high-specificity 54/94 visual guard missing');
assert(css.includes('button.sags5494DirectHit.sagsUiButton'),'guard must win even if stale sagsUiButton remains');
assert(css.includes('background:transparent!important'),'54/94 hitbox must stay transparent');
console.log('V6.4.142 fixed-ui FSAGS54/94 hitbox exclusion guard passed.');
