const fs=require('node:fs'),assert=require('node:assert/strict');
const s=fs.readFileSync(__dirname+'/../app/modules/admin-account-actions.v2.js','utf8');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
assert.match(s,/ADMIN ACCOUNT LIFECYCLE V3/);
assert.match(s,/root\.adminCreatePersonalAccount=createAccount/);
assert.match(s,/createUserWithEmailAndPassword\(email,TMP_PASS\)/);
assert.match(s,/email-already-in-use/);
assert.match(s,/signInWithEmailAndPassword\(email,TMP_PASS\)/);
assert.match(s,/recoveredOrphanAuth/);
assert.match(s,/users\.doc\(uid\)\.set/);
assert.match(s,/cred\.user\.delete\(\)/);
assert.match(s,/Xác minh users\/\{UID\} sau đăng ký không đạt/);
const del=s.indexOf('async function deleteAccount');
const direct=s.indexOf('deleteWithDefault(email,t.uid)',del);
const reset=s.indexOf('callReset(t)',del);
assert.ok(del>=0&&direct>del&&reset>direct,'DELETE must try direct default-password Auth deletion before reset fallback');
assert.match(s,/httpsCallable\('adminDeleteAuthUser'\)/);
assert.match(s,/await t\.ref\.delete\(\)/);
assert.match(s,/Không thể xóa chính tài khoản AD đang đăng nhập/);
assert.match(s,/root\.adminDeletePersonalAccount=deleteAccount/);
assert.ok(html.lastIndexOf('admin-account-actions.v2.js')>html.lastIndexOf('33-v6497-dossier-enhancements.js'),'account lifecycle override must load last');
console.log('Admin account lifecycle V3 contract passed: create recovery + direct delete first');
