const fs=require('node:fs'),assert=require('node:assert/strict');
const s=fs.readFileSync(__dirname+'/../app/modules/admin-account-actions.v2.js','utf8');
const list=fs.readFileSync(__dirname+'/../app/boot/15-v116-account-name-search.js','utf8');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
assert.match(s,/ADMIN ACCOUNT LIFECYCLE V4/);
assert.match(s,/root\.adminCreatePersonalAccount=createAccount/);
assert.match(s,/deletedCandidates/);
assert.match(s,/reuseDeletedUid/);
assert.match(s,/Firebase Auth cũ còn tồn tại · đang tạo lại hồ sơ web trên đúng UID cũ/);
assert.match(s,/deleted:false/);
assert.match(s,/recreatedFromWebDelete/);
assert.match(s,/old web-delete tombstone cleanup/);
assert.match(s,/deleted:true,deletedAtMs:now/);
assert.match(s,/WEB_DELETE_FOR_RECREATE/);
assert.match(s,/authRetainedAfterWebDelete/);
assert.doesNotMatch(s,/XÓA HOÀN TOÀN .*Xóa Firebase Authentication \+ users\/\{UID\}/s);
assert.match(list,/username==="AD"\|\|d\.deleted===true/);
assert.match(s,/Không thể xóa chính tài khoản AD đang đăng nhập/);
assert.ok(html.lastIndexOf('admin-account-actions.v2.js')>html.lastIndexOf('33-v6497-dossier-enhancements.js'),'account lifecycle override must load last');
console.log('Admin account lifecycle V4 passed: web delete frees duplicates and recreate reuses old Auth UID.');
