const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../app/core/app.v503.js','utf8');
const start=source.indexOf('(function(root) {\n    "use strict";\n    if (root.__SAGS_V2237_AUTO_SIGN_INSTALLED)');
const end=start+source.slice(start).search(/\}\)\(typeof window\s*!==\s*"undefined"\s*\?\s*window\s*:\s*globalThis\);/);
assert(start>=0&&end>start);const code=source.slice(start,end)+'})(window);';
function fixture(){let seq=0;const timers=new Map(),events={},classes=new Set(['v157-authenticated','v157-home']),notices=new Map();const calls={popup:0,toast:0,reads:0,images:0,persist:0};const meta={id:'flight-A',rosterAssignmentId:'task-A',rosterOpDate:'2026-10-06',rosterOwner:'alice'};
 const c={console,Map,Set,Promise,Uint8ClampedArray,state:{},fields:[],activeFormGroup:'fsags',currentRole:'DH',currentUserProfile:{username:'alice',fullName:'ALICE'},getSavedTemplate:()=>null,currentFlightSessionMeta:()=>meta,getComputedStyle:()=>({display:'none'}),persist:()=>calls.persist++,draw:()=>{},sessionStorage:{getItem:k=>notices.get(k),setItem:(k,v)=>notices.set(k,v)},setTimeout:fn=>{const id=++seq;timers.set(id,fn);return id},clearTimeout:id=>timers.delete(id),addEventListener:(key,fn)=>{events[key]=fn},showToast:()=>calls.toast++,sagsActionPopup:()=>calls.popup++,document:{readyState:'complete',body:{classList:{contains:n=>classes.has(n)}},getElementById:()=>null,addEventListener:(key,fn)=>{events[key]=fn},createElement:()=>({width:1,height:1,getContext:()=>({drawImage(){},getImageData:()=>({data:new Uint8ClampedArray(4)}),clearRect(){}}),toDataURL:()=> 'sig'})},sagsV470Ref:()=>({once:async()=>{calls.reads++;return{val:()=>({items:{'task-A':{user:'alice',formGroup:'fsags',assignmentLeg:'BOTH'}}})}}}),Image:class{constructor(){calls.images++;this.width=this.height=this.naturalWidth=this.naturalHeight=1}set src(v){Promise.resolve().then(()=>this.onload())}}};c.window=c;vm.createContext(c);vm.runInContext(code,c);timers.clear();async function run(){c.v2237AutoRosterSign();const batch=[...timers.values()];timers.clear();for(const fn of batch)await fn();await new Promise(r=>setImmediate(r));}return{c,calls,classes,meta,events,timers,run};}
(async()=>{
 let f=fixture();await f.run();assert.equal(f.calls.popup,0);assert.equal(f.calls.toast,0);assert.equal(f.calls.reads,0,'home must not query an old assignment');
 f.classes.delete('v157-home');await f.run();await f.run();assert.equal(f.calls.popup,0,'missing signature must not block the operator');assert.equal(f.calls.toast,1,'show the hint once per account/assignment');
 f=fixture();f.classes.delete('v157-home');f.meta.rosterOwner='bob';f.c.getSavedTemplate=()=>({signature:'sig'});await f.run();assert.equal(f.calls.reads,0);assert.equal(f.calls.images,0);
 f=fixture();f.classes.delete('v157-home');f.c.getSavedTemplate=()=>({signature:'sig'});let resolve;f.c.sagsV470Ref=()=>({once:()=>new Promise(r=>resolve=r)});const job=f.run();await Promise.resolve();f.c.currentUserProfile={username:'bob'};resolve({val:()=>({items:{'task-A':{user:'alice',formGroup:'fsags'}}})});await job;assert.deepEqual(Object.keys(f.c.state),[],'account switch must discard the pending auto-sign');assert.equal(f.calls.images,0);
 f=fixture();f.classes.delete('v157-home');f.c.getSavedTemplate=()=>({signature:'sig',fullname:'ALICE'});await f.run();assert.equal(f.c.state.sigArr,'sig');assert.equal(f.c.state.sigDep,'sig');assert.equal(f.c.state.bbbtSigAgent1,'sig');assert.equal(f.calls.images,1,'trim the same signature once for ARR/DEP/BBBT');assert.equal(f.calls.persist,1);await f.run();assert.equal(f.calls.persist,1,'completed auto-sign must not repeat');
 const before=f.timers.size;f.events.click({target:{closest:()=>null}});assert.equal(f.timers.size,before,'unrelated UI taps must not schedule auto-sign');
 console.log('Auto-sign context passed: home quiet, no blocking missing-template popup, verified owner, account race discarded, one signature decode.');
})().catch(e=>{console.error(e);process.exitCode=1});
