const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),css=read('app/styles/fixed-ui-rule-v64113.css'),js=read('app/boot/32-fixed-ui-rule-v64113.js'),rules=read('PROJECT_RULES.md');
assert(html.includes('fixed-ui-rule-v64113.css'),'fixed UI stylesheet must be loaded');
assert(html.includes('32-fixed-ui-rule-v64113.js'),'fixed UI runtime guard must be loaded');
assert(html.indexOf('mobile-navy-v64106.css')<html.indexOf('fixed-ui-rule-v64113.css'),'fixed UI stylesheet must load last');
assert(css.includes('--sags-button-radius:12px'),'canonical radius missing');
assert(!css.includes('999px'),'fixed UI must not introduce pill radius');
assert(css.includes('bottom:calc(var(--sags-nav-bar-height) + env(safe-area-inset-bottom))'),'form dock must sit above nav');
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'Menu/Home two-column row missing');
assert(css.includes('grid-template-columns:repeat(var(--sags-action-count,4),minmax(0,1fr))'),'compact form action row missing');
assert(css.includes('--sags-form-dock-height,56px'),'content must reserve measured dock height');
assert(css.includes('V6.4.114 PROJECT-WIDE BUTTON AUDIT'),'project-wide button audit guard missing');
assert(css.includes('input[type="submit"]'),'submit controls must inherit fixed UI geometry');
assert(css.includes('.templateActions'),'legacy modal action rows must be normalized');
assert(css.includes('V6.4.126 COMPACT QUICK INPUT'),'compact quick-input rule missing');
assert(css.includes('#quickTimeModal .quickTimeNow'),'quick-time clock action must have a compact override');
assert(css.includes('#quickTimeModal .quickTimeFooterActions button'),'quick-time footer actions must follow compact button geometry');
assert(js.includes("v163SignBtn"),'existing signature action must be preserved in the action row');
assert(js.includes('tagLegacyButtons'),'dynamic legacy buttons must be tagged by runtime guard');
assert(js.includes('pendingScopes')&&js.includes('queueScope'),'dynamic UI normalization must batch only changed DOM scopes');
assert(!js.includes('root.addEventListener(\'resize\',schedule'),'resize must not trigger a full-document normalization scan');
assert(js.includes('HO SO BIEU MAU')&&js.includes('CHO NHAN'),'duplicate status cleanup missing');
assert(rules.includes('THÊM CHỨC NĂNG MỚI NHƯNG KHÔNG THÊM MỘT PHONG CÁCH NÚT MỚI'),'project UI rule missing');
console.log('Fixed UI rule checks passed.');
