const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const fixed=read('app/boot/32-fixed-ui-rule-v64113.js');
const mobile=read('app/boot/36-v6496-approved-mobile-ui.js');
assert(fixed.includes("V6.4.129-MOBILE-UI-STABILITY-01"),'fixed UI stability build marker');
assert(fixed.includes("dockObserver.observe(row,{subtree:true,childList:true,attributes:true,attributeFilter:['class','style','hidden']})"),'dock visibility observation must be scoped to form actions');
assert(fixed.includes("}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});"),'global observer must be structural/text only');
assert(!fixed.includes("observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true"),'global class/style observer must stay removed');
assert(fixed.includes("r.type==='characterData'&&needsCopyCleanup(r.target)"),'unrelated live text updates must not trigger UI subtree scans');
assert(mobile.includes('if(scheduled)return;'),'mobile visual tagger must coalesce mutation bursts');
assert(mobile.includes('scheduled=false;apply()'),'mobile visual tagger must release the animation-frame lock');
console.log('V6.4.129 mobile observer stability guard passed.');
