const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const src=read('app/modules/fsags208-workspace.v1.js'),runtime=read('app/generated/runtime-1.js'),cargo=read('app/modules/cargo-all-flights.v1.js');
assert(src.includes('function removeDeprecatedBackControls()'));
assert(!src.includes('function stableMyFlightBack(ev)'));
assert(!src.includes('new MutationObserver(()=>ensureStableMyFlightBack())'));
assert(runtime.includes('head.querySelector("#v644MyFlightBack")?.remove()'));
assert(runtime.includes('close.textContent="☰ MENU"'));
assert(!runtime.includes('title.textContent="📦 DANH SÁCH CHUYẾN BAY"'));
assert(src.includes('async function workspaceRows('));
assert(src.includes('function cargoSharedCard('));
assert(src.includes('shared.cardHtml(group,date)'));
assert(src.includes("title.textContent='✈ MY FLIGHT'"));
assert(src.includes('CHUYẾN ĐÃ HOÀN TẤT'));
assert(src.includes('v1199DirectTask,.v1199TaskBtn'));
assert(src.includes('__sagsCargoUnifiedV64128'));
assert(src.includes('listRows:workspaceRows'));
assert(!cargo.includes('Tất cả chuyến bay'));
assert(!cargo.includes('DANH SÁCH CHUYẾN BAY'));
console.log('V6.4.128 unified Cargo MY FLIGHT UI guard passed.');
