const assert=require('assert/strict'),fs=require('fs'),R=require('../app/modules/roster-responsibility.v1.js');
const date='2026-10-04',accounts=['KIEN','PHUONG','HUY','VU','ADMIN'].map(username=>({username,active:true}));
const base={opDate:date,date:'04/10/2026',flightId:'FLT_VN123_124',arrFlight:'VN123',depFlight:'VN124',flightRaw:'VN123/124',flightName:'VN123 / VN124',rowNo:2,route:'HAN-CXR-HAN',sta:'10:00',std:'11:00'};
const allocate=(c,l,b=base)=>R.allocate(b,c,l),clone=v=>v==null?v:JSON.parse(JSON.stringify(v)),canon=x=>R.canonical(x?.formGroup||x);
function db(initial={}){const data=clone(initial);let writes=0;const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],data)??null;
 const set=(p,v)=>{const a=p.split('/').filter(Boolean);let x=data;for(const k of a.slice(0,-1))x=x[k]??={};if(v===null)delete x[a.at(-1)];else x[a.at(-1)]=clone(v)};
 const ref=p=>({once:async()=>({val:()=>clone(get(p))}),update:async patch=>{const keys=Object.keys(patch);for(const a of keys)for(const b of keys)if(a!==b&&b.startsWith(a+'/'))throw Error('overlapping RTDB paths '+a+' / '+b);for(const [k,v]of Object.entries(patch))set(p?(p+'/'+k):k,v);writes++},transaction:async fn=>{const out=fn(clone(get(p)));if(out===undefined)return {committed:false,snapshot:{val:()=>clone(get(p))}};set(p,out);writes++;return {committed:true,snapshot:{val:()=>clone(out)}}}});return {data,get,ref,get writes(){return writes}}}
function fixture(initial){const store=db(initial);let user={username:'ADMIN',role:'AD'},time=1000;const svc=R.createService({ref:store.ref,actor:()=>user,now:()=>++time,accounts:async()=>accounts,seed:()=>({date:'04/10/2026',fltBefore:'VN123',fltAfter:'VN124'})});return {store,svc,as:(username,role='DH')=>{user={username,role}},preview:(records,options={})=>svc.preview(records,{date,...options}),publish:async(records,options={})=>{const p=await svc.preview(records,{date,...options});const result=await svc.publish(p);return {p,result}}}}
function activeItems(f,flightId=base.flightId){return Object.values(f.store.get('roster_manifests/'+date+'/items')||{}).filter(x=>x&&x.active!==false&&(!flightId||x.flightId===flightId))}
function byForm(items,form){return items.filter(x=>canon(x)===form)}
const results=[];async function test(letter,description,fn){try{await fn();results.push({case:letter,result:'PASS',description});console.log(letter+' PASS '+description)}catch(e){results.push({case:letter,result:'FAIL',description,error:e.message});console.error(letter+' FAIL',e);process.exitCode=1}}
(async()=>{
 await test('A','FIRST: COR=KIEN, LD=PHUONG => 42.1 + 55.1',async()=>{const f=fixture(),rows=allocate('KIEN','PHUONG');assert.deepEqual(rows.map(x=>[x.user,canon(x),x.assignmentLeg]),[['KIEN','FSAGS421','TURN'],['PHUONG','FSAGS551','TURN']]);await f.publish(rows);assert.deepEqual(activeItems(f).map(x=>[x.user,canon(x)]),[['KIEN','FSAGS421'],['PHUONG','FSAGS551']])});
 await test('B','FIRST: COR=LD=KIEN => one 42.3',async()=>{const f=fixture(),rows=allocate('KIEN','KIEN');assert.equal(rows.length,1);assert.equal(canon(rows[0]),'FSAGS423');await f.publish(rows);assert.equal(activeItems(f).length,1);assert.equal(canon(activeItems(f)[0]),'FSAGS423')});
 await test('C','UPDATE COR handover keeps SAME 42.1; LD unchanged',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const before=byForm(activeItems(f),'FSAGS421')[0],fid=before.formInstanceId;const {p}=await f.publish(allocate('KIEN / HUY','PHUONG'));assert.equal(p.counts.HANDOVER,1);const now=activeItems(f),c=byForm(now,'FSAGS421')[0],l=byForm(now,'FSAGS551')[0];assert.equal(c.user,'HUY');assert.equal(c.formInstanceId,fid);assert.equal(l.user,'PHUONG')});
 await test('D','UPDATE both columns to HUY preserves 42.1 + 55.1, no 42.3',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const before=activeItems(f),f421=byForm(before,'FSAGS421')[0].formInstanceId,f551=byForm(before,'FSAGS551')[0].formInstanceId;await f.publish(allocate('KIEN / HUY','PHUONG / HUY'));const now=activeItems(f);assert.equal(byForm(now,'FSAGS423').length,0);assert.equal(byForm(now,'FSAGS421')[0].user,'HUY');assert.equal(byForm(now,'FSAGS421')[0].formInstanceId,f421);assert.equal(byForm(now,'FSAGS551')[0].user,'HUY');assert.equal(byForm(now,'FSAGS551')[0].formInstanceId,f551)});
 await test('E','UPDATE COR/LD to different successors preserves each lineage',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const before=activeItems(f),a=byForm(before,'FSAGS421')[0].formInstanceId,b=byForm(before,'FSAGS551')[0].formInstanceId;await f.publish(allocate('KIEN / HUY','PHUONG / VU'));const now=activeItems(f);assert.deepEqual(now.map(x=>[x.user,canon(x),x.formInstanceId]),[['HUY','FSAGS421',a],['VU','FSAGS551',b]])});
 await test('F','FIRST 42.3 then COR handover keeps SAME 42.3 only',async()=>{const f=fixture();await f.publish(allocate('KIEN','KIEN'));const fid=activeItems(f)[0].formInstanceId;await f.publish(allocate('KIEN / HUY','KIEN'));const now=activeItems(f);assert.equal(now.length,1);assert.equal(now[0].user,'HUY');assert.equal(canon(now[0]),'FSAGS423');assert.equal(now[0].formInstanceId,fid)});
 await test('G','FIRST 42.3 then split LD => SAME 42.3 to HUY + NEW 55.1 PHUONG, no 42.1',async()=>{const f=fixture();await f.publish(allocate('KIEN','KIEN'));const fid=activeItems(f)[0].formInstanceId;const {p}=await f.publish(allocate('KIEN / HUY','KIEN / PHUONG'));const now=activeItems(f);assert.equal(byForm(now,'FSAGS421').length,0);assert.equal(byForm(now,'FSAGS423')[0].user,'HUY');assert.equal(byForm(now,'FSAGS423')[0].formInstanceId,fid);assert.equal(byForm(now,'FSAGS551')[0].user,'PHUONG');assert.equal(p.counts.NEW_FORM,1);assert.equal(p.counts.HANDOVER,1)});
 await test('H','existing 42.1 + 55.1 never collapse when currentOwner converges',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));await f.publish(allocate('KIEN / HUY','PHUONG / HUY'));const now=activeItems(f);assert.equal(byForm(now,'FSAGS423').length,0);assert.equal(byForm(now,'FSAGS421').length,1);assert.equal(byForm(now,'FSAGS551').length,1);assert(now.every(x=>x.user==='HUY'))});
 await test('I','slash chain KIEN / VU / HUY persists chronological handover history',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));await f.publish(allocate('KIEN / VU','PHUONG'));await f.publish(allocate('KIEN / VU / HUY','PHUONG'));const x=byForm(activeItems(f),'FSAGS421')[0],ws=f.store.get('roster_flight_workspaces/'+x.formInstanceId);assert.deepEqual(ws.assignmentTimeline,[['KIEN'],['VU'],['HUY']]);assert.equal(ws.currentOwner,'HUY')});
 await test('J','slash parses as handover timeline, not ARR/DEP',()=>{const x=R.parseLegs('KIEN / HUY',base,'Grnd_Cor');assert.deepEqual(x.history,[['KIEN'],['HUY']]);assert.deepEqual(x.currentUsers,['HUY']);assert.equal('ARR' in x,false);assert.equal('DEP' in x,false)});
 await test('K','slash never throws leg/flight mismatch error',()=>{const oneLeg={...base,depFlight:'',flightRaw:'VN123'};assert.doesNotThrow(()=>allocate('KIEN / HUY','PHUONG',oneLeg));assert.doesNotThrow(()=>R.parseLegs('KIEN / VU / HUY',oneLeg,'Grnd_Cor'))});
 await test('L','open/view/prefill only is not a meaningful edit',async()=>{assert.equal(R.meaningful({state:{date:'04/10/2026'},currentPage:6,scrollY:100},{state:{date:'04/10/2026'}}),false);const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const a=byForm(activeItems(f),'FSAGS421')[0];f.as('KIEN');const opened=await f.svc.acquire(a.assignmentId);assert.equal(!!opened.form.meaningfulEdited,false)});
 await test('M','meaningful form data survives handover',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const a=byForm(activeItems(f),'FSAGS421')[0];f.as('KIEN');await f.svc.acquire(a.assignmentId);await f.svc.save(a.assignmentId,{state:{h5Start:'10:02',signature:'data:image/png;base64,AAAA'}});f.as('ADMIN','AD');await f.publish(allocate('KIEN / HUY','PHUONG'));const x=byForm(activeItems(f),'FSAGS421')[0];assert.equal(x.formInstanceId,a.formInstanceId);assert.equal(f.store.get('roster_flight_workspaces/'+a.formInstanceId+'/envelope/state/h5Start'),'10:02')});
 await test('N','old mailbox becomes inactive after handover',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const a=byForm(activeItems(f),'FSAGS421')[0];await f.publish(allocate('KIEN / HUY','PHUONG'));assert.equal(f.store.get('roster_mail/KIEN/items/'+a.assignmentId+'/active'),false);assert.equal(f.store.get('roster_sessions/'+a.assignmentId+'/claimStatus'),'REVOKED')});
 await test('O','new mailbox active and points to SAME formInstanceId',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const old=byForm(activeItems(f),'FSAGS421')[0];await f.publish(allocate('KIEN / HUY','PHUONG'));const x=byForm(activeItems(f),'FSAGS421')[0],mail=f.store.get('roster_mail/HUY/items/'+x.assignmentId);assert.equal(mail.active,true);assert.equal(mail.formInstanceId,old.formInstanceId)});
 await test('P','owner-only change never duplicates the form instance',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const count1=Object.keys(f.store.get('roster_flight_workspaces')||{}).length;await f.publish(allocate('KIEN / HUY','PHUONG'));const count2=Object.keys(f.store.get('roster_flight_workspaces')||{}).length;assert.equal(count2,count1)});
 await test('Q','new 55.1 from split 42.3 is created exactly once',async()=>{const f=fixture();await f.publish(allocate('KIEN','KIEN'));const update=allocate('KIEN / HUY','KIEN / PHUONG');await f.publish(update);const rev=f.store.get('roster_manifests/'+date+'/rosterRevision'),count=Object.keys(f.store.get('roster_flight_workspaces')||{}).length;const {result}=await f.publish(update);assert.equal(result.noChange,true);assert.equal(result.revision,rev);assert.equal(Object.keys(f.store.get('roster_flight_workspaces')||{}).length,count);assert.equal(byForm(activeItems(f),'FSAGS551').length,1)});
 await test('R','re-uploading the same revision/file is idempotent',async()=>{const f=fixture(),rows=allocate('KIEN','PHUONG');await f.publish(rows,{fileHash:'same'});const before=activeItems(f).map(x=>x.assignmentId).sort(),p=await f.preview(rows,{fileHash:'same'}),r=await f.svc.publish(p);assert.equal(r.noChange,true);assert.equal(r.revision,1);assert.deepEqual(activeItems(f).map(x=>x.assignmentId).sort(),before)});
 await test('S','stale preview is rejected by rosterRevision',async()=>{const f=fixture();await f.publish(allocate('KIEN','PHUONG'));const stale=await f.preview(allocate('KIEN / HUY','PHUONG')),fresh=await f.preview(allocate('KIEN / VU','PHUONG'));await f.svc.publish(fresh);await assert.rejects(()=>f.svc.publish(stale),/revision|cũ/)});
 await test('T','PARTIAL update never revokes flights outside file scope',async()=>{const f=fixture(),otherBase={...base,flightId:'FLT_VN200_201',arrFlight:'VN200',depFlight:'VN201',flightRaw:'VN200/201',flightName:'VN200 / VN201',rowNo:3},other=allocate('VU','VU',otherBase);await f.publish([...allocate('KIEN','PHUONG'),...other]);const otherId=other[0].formInstanceId;await f.publish(allocate('KIEN / HUY','PHUONG'),{mode:'PARTIAL',scopeFlights:[base.flightId]});const now=activeItems(f,'FLT_VN200_201');assert.equal(now.length,1);assert.equal(now[0].formInstanceId,otherId);assert.equal(now[0].user,'VU')});
 await test('U','FIRST import may already contain LD handover PHUONG / HUY',async()=>{const f=fixture(),rows=allocate('KIEN','PHUONG / HUY');assert.deepEqual(rows.map(x=>[x.user,canon(x)]),[['KIEN','FSAGS421'],['HUY','FSAGS551']]);const p=await f.preview(rows);assert.deepEqual(p.errors,[]);await f.svc.publish(p);const now=activeItems(f),ld=byForm(now,'FSAGS551')[0],ws=f.store.get('roster_flight_workspaces/'+ld.formInstanceId);assert.equal(ld.user,'HUY');assert.equal(ld.originalOwner,'PHUONG');assert.deepEqual(ws.assignmentTimeline,[['PHUONG'],['HUY']])});
 await test('V','FIRST import can reconstruct original 42.3 then split LD from timeline',async()=>{const f=fixture(),rows=allocate('KIEN / HUY','KIEN / PHUONG');assert.deepEqual(rows.map(x=>[x.user,canon(x)]),[['HUY','FSAGS423'],['PHUONG','FSAGS551']]);const p=await f.preview(rows);assert.deepEqual(p.errors,[]);await f.svc.publish(p);const now=activeItems(f),f423=byForm(now,'FSAGS423')[0],f551=byForm(now,'FSAGS551')[0];assert.equal(f423.originalOwner,'KIEN');assert.equal(f551.originalOwner,'KIEN');assert.deepEqual(f423.assignmentTimeline,[['KIEN'],['HUY']]);assert.deepEqual(f551.assignmentTimeline,[['KIEN'],['PHUONG']])});
 const path=process.env.SAGS_ROSTER_RESULTS;if(path)fs.writeFileSync(path,JSON.stringify(results,null,2));if(process.exitCode)throw Error('Roster responsibility cases failed');console.log('A–V passed: roster lineage, first-import handover, split responsibility, mailbox, edit preservation, revision and partial-update rules.');
})().catch(e=>{console.error(e);process.exitCode=1});