const assert=require('assert/strict'),fs=require('fs'),R=require('../app/modules/roster-responsibility.v1.js');
const date='2026-10-04',accounts=['KIENNT','VUTP','PHONGNV','DATVH'].map(username=>({username,active:true}));
const base={opDate:date,date:'04/10/2026',flightId:'FLT_VN123_124',arrFlight:'VN123',depFlight:'VN124',flightRaw:'VN123/124',flightName:'VN123 / VN124',rowNo:2,route:'HAN-CXR-HAN',sta:'10:00',std:'11:00'};
const allocate=(c,l,b=base)=>R.allocate(b,c,l);
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function db(initial={}){const data=clone(initial);let writes=0;const get=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],data)??null;
 const set=(p,v)=>{const a=p.split('/').filter(Boolean);let x=data;for(const k of a.slice(0,-1))x=x[k]??={};if(v===null)delete x[a.at(-1)];else x[a.at(-1)]=clone(v)};
 const ref=p=>({once:async()=>({val:()=>clone(get(p))}),update:async patch=>{const keys=Object.keys(patch);for(const a of keys)for(const b of keys)if(a!==b&&b.startsWith(a+'/'))throw Error('overlapping RTDB paths '+a+' / '+b);for(const [k,v]of Object.entries(patch))set(p?(p+'/'+k):k,v);writes++},transaction:async fn=>{const out=fn(clone(get(p)));if(out===undefined)return {committed:false,snapshot:{val:()=>clone(get(p))}};set(p,out);writes++;return {committed:true,snapshot:{val:()=>clone(out)}}}});return {data,get,ref,get writes(){return writes}}}
function fixture(initial){const store=db(initial);let user={username:'ADMIN',role:'AD'},time=1000;const svc=R.createService({ref:store.ref,actor:()=>user,now:()=>++time,accounts:async()=>accounts,seed:()=>({date:'04/10/2026',fltBefore:'VN123',fltAfter:'VN124'})});return {store,svc,as:(username,role='DH')=>{user={username,role}},publish:async(records,options={})=>{const p=await svc.preview(records,{date,...options});await svc.publish(p);return p}}}
const results=[];async function test(letter,description,fn){try{await fn();results.push({case:letter,result:'PASS',description});console.log(letter+' PASS '+description)}catch(e){results.push({case:letter,result:'FAIL',description,error:e.message});console.error(letter+' FAIL',e);process.exitCode=1}}
(async()=>{
 await test('A','COR=LD gives 42.3 ARR',()=>{const x=allocate('KIENNT /','KIENNT /');assert.equal(x.length,1);assert.equal(x[0].formGroup,'fsags');assert.equal(x[0].assignmentLeg,'ARR')});
 await test('B','different COR/LD gives 42.1 and 55.1 ARR',()=>assert.deepEqual(allocate('KIENNT /','VUTP /').map(x=>[x.user,x.formGroup,x.assignmentLeg]),[['KIENNT','fsags421','ARR'],['VUTP','fsags551','ARR']]));
 await test('C','42.3 ARR; 42.1+55.1 DEP',()=>assert.deepEqual(allocate('KIENNT / VUTP','KIENNT / PHONGNV').map(x=>[x.formGroup,x.assignmentLeg]),[['fsags','ARR'],['fsags421','DEP'],['fsags551','DEP']]));
 await test('D','42.1+55.1 ARR; 42.3 DEP',()=>assert.deepEqual(allocate('KIENNT / VUTP','PHONGNV / VUTP').map(x=>[x.formGroup,x.assignmentLeg]),[['fsags421','ARR'],['fsags551','ARR'],['fsags','DEP']]));
 await test('E','same user ARR/DEP uses one form and TURN',()=>{const x=allocate('KIENNT / KIENNT','PHONGNV / PHONGNV').filter(x=>x.formGroup==='fsags421');assert.equal(x.length,1);assert.equal(x[0].assignmentLeg,'TURN')});
 await test('F','different users continue the same shared form data',async()=>{const f=fixture(),rows=allocate('KIENNT / VUTP','PHONGNV / DATVH'),a=rows.find(x=>x.formGroup==='fsags421'&&x.assignmentLeg==='ARR'),b=rows.find(x=>x.formGroup==='fsags421'&&x.assignmentLeg==='DEP');assert.equal(a.formInstanceId,b.formInstanceId);await f.publish(rows);f.as('KIENNT');await f.svc.acquire(a.assignmentId);await f.svc.complete(a.assignmentId,{state:{date:'04/10/2026',fltBefore:'VN123',fltAfter:'VN124',h5Start:'10:01'}});f.as('VUTP');const open=await f.svc.acquire(b.assignmentId);assert.equal(open.form.envelope.state.h5Start,'10:01')});
 await test('G','DEP structure update preserves ARR',async()=>{const f=fixture(),old=allocate('KIENNT / VUTP','KIENNT / VUTP');await f.publish(old);const p=await f.publish(allocate('KIENNT / VUTP','KIENNT / PHONGNV'));const a=old.find(x=>x.assignmentLeg==='ARR');assert.equal(p.next[a.assignmentId].active,true);assert.equal(p.next[a.assignmentId].formInstanceId,a.formInstanceId)});
 await test('H','ARR structure update preserves DEP',async()=>{const f=fixture(),old=allocate('KIENNT / VUTP','PHONGNV / VUTP');await f.publish(old);const p=await f.publish(allocate('KIENNT / VUTP','KIENNT / VUTP'));const d=old.find(x=>x.assignmentLeg==='DEP');assert.equal(p.next[d.assignmentId].active,true)});
 await test('I','unedited owner transfers immediately',async()=>{const f=fixture();await f.publish(allocate('KIENNT /','PHONGNV /'));const p=await f.publish(allocate('VUTP /','PHONGNV /'));assert.equal(p.counts.REASSIGN,1);assert.equal(p.counts.PRESERVE,0)});
 await test('J','open/focus/prefill is not meaningful edit',async()=>{assert.equal(R.meaningful({state:{date:'04/10/2026'},currentPage:9},{state:{date:'04/10/2026'}}),false);const f=fixture(),rows=allocate('KIENNT /','PHONGNV /');await f.publish(rows);const a=rows[0];f.as(a.user);const o=await f.svc.acquire(a.assignmentId);assert(!o.form.meaningfulEdited);f.as('ADMIN','AD');await f.publish(allocate('VUTP /','PHONGNV /'));assert.equal(f.store.get('roster_mail/KIENNT/items/'+a.assignmentId+'/active'),false)});
 await test('K','edited form data is preserved on reassignment',async()=>{const f=fixture(),rows=allocate('KIENNT /','PHONGNV /');await f.publish(rows);const a=rows[0];f.as(a.user);await f.svc.acquire(a.assignmentId);await f.svc.save(a.assignmentId,{state:{h5Start:'10:02',signature:'data:image/png;base64,AAAA',attachments:['file1']}});f.as('ADMIN','AD');const p=await f.publish(allocate('VUTP /','PHONGNV /'));assert(p.counts.PRESERVE>0);assert.equal(f.store.get('roster_flight_workspaces/'+a.formInstanceId+'/envelope/state/h5Start'),'10:02')});
 await test('L','handover keeps form identity and exclusive lock',async()=>{const f=fixture(),rows=allocate('KIENNT / VUTP','PHONGNV / DATVH'),a=rows[0],b=rows.find(x=>x.formInstanceId===a.formInstanceId&&x.user==='VUTP');await f.publish(rows);f.as('VUTP');await assert.rejects(()=>f.svc.acquire(b.assignmentId),/chưa bàn giao/);f.as('KIENNT');await f.svc.acquire(a.assignmentId);await f.svc.complete(a.assignmentId,{state:{h5Start:'10:00'}});f.as('VUTP');assert.equal((await f.svc.acquire(b.assignmentId)).form.formInstanceId,a.formInstanceId)});
 await test('M','partial upload preserves absent flights',async()=>{const f=fixture(),other=allocate('DATVH /','DATVH /',{...base,flightId:'FLT_OTHER',arrFlight:'VN200',depFlight:'VN201'});await f.publish([...allocate('KIENNT /','PHONGNV /'),...other]);await f.publish(allocate('VUTP /','PHONGNV /'));assert.equal(f.store.get('roster_manifests/'+date+'/items/'+other[0].assignmentId+'/active'),true)});
 await test('N','full snapshot revokes absent assignments without deleting',async()=>{const f=fixture(),old=allocate('KIENNT /','PHONGNV /'),other=allocate('DATVH /','DATVH /',{...base,flightId:'FLT_OTHER'});await f.publish([...old,...other]);await f.publish(old,{mode:'FULL'});const x=f.store.get('roster_manifests/'+date+'/items/'+other[0].assignmentId);assert.equal(x.active,false);assert(x.formInstanceId)});
 await test('O','stale AD preview rejected',async()=>{const f=fixture(),p=await f.svc.preview(allocate('KIENNT /','PHONGNV /'),{date}),q=await f.svc.preview(allocate('VUTP /','PHONGNV /'),{date});await f.svc.publish(q);await assert.rejects(()=>f.svc.publish(p),/revision|cũ/)});
 await test('P','identical re-upload is a no-op',async()=>{const f=fixture(),rows=allocate('KIENNT /','PHONGNV /');await f.publish(rows);const p=await f.svc.preview(rows,{date,fileHash:'same'}),r=await f.svc.publish(p);assert(r.noChange);assert.equal(r.revision,1)});
 await test('Q','unknown account blocks whole batch',async()=>{const f=fixture(),p=await f.svc.preview(allocate('UNKNOWN /','PHONGNV /'),{date});assert(p.errors.length);await assert.rejects(()=>f.svc.publish(p),/không tồn tại/);assert.equal(f.store.get('roster_manifests/'+date),null)});
 await test('R','one active instance per flight/canonical form',async()=>{const f=fixture(),rows=allocate('KIENNT / VUTP','PHONGNV / DATVH');await f.publish(rows);assert.equal(Object.keys(f.store.get('roster_flight_workspaces')).length,2);assert.equal(new Set(rows.map(x=>x.formInstanceId)).size,2)});
 await test('S','duplicate responsibility blocked; ambiguous slash blocked',()=>{const rows=allocate('KIENNT /','PHONGNV /');assert(R.plan({date,records:[...rows,...rows],accounts}).errors.length);assert.throws(()=>allocate('KIENNT / VUTP / DATVH','PHONGNV'),/nhiều dấu/)});
 await test('T','ARR completion does not complete DEP or 55.1',async()=>{const f=fixture(),rows=allocate('KIENNT / VUTP','PHONGNV / DATVH'),a=rows[0];await f.publish(rows);f.as(a.user);await f.svc.acquire(a.assignmentId);const done=await f.svc.complete(a.assignmentId,{state:{h5Start:'10:00'}});assert.equal(done.formCompletion,'PENDING');assert(Object.values(done.assignments).some(x=>x.completion==='PENDING'));assert.equal(f.store.get('roster_sessions/'+rows.find(x=>x.formGroup==='fsags551').assignmentId+'/assignmentCompletion'),null)});
 await test('U','ARR/DEP user A/B share one workspace',()=>{const x=allocate('KIENNT / VUTP','PHONGNV / DATVH').filter(x=>x.formGroup==='fsags421');assert.equal(x.length,2);assert.equal(x[0].workspaceKey,x[1].workspaceKey);assert(!x[0].workspaceKey.includes('KIENNT'))});
 await test('V','same user both legs uses same local form ID',()=>{const x=allocate('KIENNT / KIENNT','PHONGNV / PHONGNV')[0],f=fixture();assert.equal(f.svc.localId(x),'form-'+x.formInstanceId);assert.equal(x.assignmentLeg,'TURN')});
 await test('W','old mailbox and flight assignment are inactive after DEP replacement',async()=>{const f=fixture(),old=allocate('KIENNT / VUTP','PHONGNV / DATVH');await f.publish(old);const dep=old.find(x=>x.user==='VUTP');await f.publish(allocate('KIENNT / PHONGNV','PHONGNV / DATVH'));assert.equal(f.store.get('roster_mail/VUTP/items/'+dep.assignmentId+'/active'),false);assert.equal(f.store.get('flight_records/'+date+'/'+base.flightId+'/assignments/'+dep.assignmentId+'/active'),false);assert.equal(f.store.get('roster_sessions/'+dep.assignmentId+'/claimStatus'),'REVOKED')});
 await test('X','form schema change retains old data and audit',async()=>{const f=fixture(),old=allocate('KIENNT /','KIENNT /'),a=old[0];await f.publish(old);f.as(a.user);await f.svc.acquire(a.assignmentId);await f.svc.save(a.assignmentId,{state:{h5Start:'10:02'}});f.as('ADMIN','AD');await f.publish(allocate('VUTP /','PHONGNV /'));const form=f.store.get('roster_flight_workspaces/'+a.formInstanceId);assert.equal(form.envelope.state.h5Start,'10:02');assert(Object.keys(form.audit).length);const newId=allocate('VUTP /','PHONGNV /')[0].formInstanceId;assert.equal(f.store.get('roster_flight_workspaces/'+newId+'/envelope/state/h5Start'),null)});
 // Transaction/error paths beyond A-X.
 const f=fixture(),rows=allocate('KIENNT /','PHONGNV /');await f.publish(rows);f.as('KIENNT');await f.svc.acquire(rows[0].assignmentId);await f.svc.markDirty(rows[0].assignmentId);f.as('ADMIN','AD');const p=await f.svc.preview(allocate('VUTP /','PHONGNV /'),{date});await assert.rejects(()=>f.svc.publish(p),/chưa lưu/);assert.equal(f.store.get('roster_manifests/'+date+'/rosterRevision'),1);
 assert(allocate('KIENNT /','PHONGNV /',{...base,arrFlight:'VZ101',depFlight:'VZ102'}).some(x=>x.formGroup==='tvjgof035'));
 assert.equal(R.meaningful({state:{attachment:['x']}},{state:{attachment:[]}}),true);
 const co=fixture(),cr=allocate('KIENNT,VUTP / DATVH','KIENNT,VUTP / DATVH');await co.publish(cr);co.as('KIENNT');await co.svc.acquire(cr[0].assignmentId);await co.svc.complete(cr[0].assignmentId,{state:{h5Start:'10:01'}});const support=cr.find(x=>x.user==='VUTP');assert.equal(co.store.get('roster_sessions/'+support.assignmentId+'/assignmentCompletion'),'COMPLETED');co.as('DATVH');await co.svc.acquire(cr.find(x=>x.user==='DATVH').assignmentId);
 const pages=fixture();await pages.publish(allocate('KIENNT /','PHONGNV /'));for(const x of allocate('KIENNT /','PHONGNV /'))assert.equal(pages.store.get('roster_flight_workspaces/'+x.formInstanceId+'/envelope/currentPage'),x.formGroup==='fsags421'?6:9);
 assert.equal(R.meaningful({state:{},attachments:['x']},{state:{},attachments:[]}),true);
 const path=process.env.SAGS_ROSTER_RESULTS;if(path)fs.writeFileSync(path,JSON.stringify(results,null,2));if(process.exitCode)throw Error('Roster responsibility cases failed');console.log('A–X passed; dirty lock, attachment edit, airline policy compatibility passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
