const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),h=read('index.html');
const scripts=[...h.matchAll(/<script\b[^>]*src=["'](\.\/[^"'?]+)[^"']*["'][^>]*>/g)].map(m=>m[1]);
const css=[...h.matchAll(/<link\b[^>]*rel=["']stylesheet["'][^>]*href=["'](\.\/[^"'?]+)[^"']*["'][^>]*>/g)].map(m=>m[1]);
assert.equal(new Set(scripts).size,scripts.length,'startup must not execute same local script twice');
const sizes=scripts.map(p=>({p,bytes:fs.statSync(path.join(root,p)).size})),bytes=sizes.reduce((n,x)=>n+x.bytes,0),max=sizes.reduce((a,b)=>a.bytes>b.bytes?a:b,{p:'',bytes:0});
assert(scripts.length<=53,'startup local scripts <= 53 including the post-login unlock hotfix, got '+scripts.length);
assert(css.length<=16,'startup stylesheets <= 16 (includes final FIXED UI override), got '+css.length);
assert(bytes<2700000,'startup JS budget < 2.7MB, got '+bytes);
assert(max.bytes<400000,'no executed startup JS asset may reach 400KB; largest '+max.p+' = '+max.bytes);
assert(scripts.includes('./app/modules/flight-governance.v1.js'),'governance engine must load');
assert(scripts.includes('./app/modules/post-login-unlock.v64123.js'),'post-login unlock hotfix must execute at startup');
assert(scripts.some(p=>p.includes('startup-bundle-')),'safe IIFE bundles must be active');
assert(!scripts.includes('./app/generated/startup-bundle-1.js'),'runtime 2-5 must not be rebound into one large startup bundle');
for(const n of [2,3,4,5])assert(scripts.includes('./app/generated/runtime-'+n+'.js'),'runtime-'+n+' must load independently for cache reuse');
assert(!scripts.some(p=>/app\/core\/(?:app\.v503|runtime\.v503hf2\.bundle)\.js$/.test(p)),'source monoliths must never execute in startup');
assert(css.some(p=>p.includes('legacy-ui-bundle-')),'legacy CSS clusters must be bundled');
const sw=read('service-worker.js'),bootstrap=JSON.parse(sw.match(/const SAGS_BOOTSTRAP=(\[[^\n]+\]);/)[1]);
for(const p of [...scripts,...css])assert(bootstrap.includes(p),'offline bootstrap misses '+p);
console.log('Startup/PWA optimized: '+scripts.length+' scripts, '+css.length+' styles, '+bytes+' bytes; largest '+max.p+' '+max.bytes+' bytes');
