const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),h=read('index.html');
const scripts=[...h.matchAll(/<script\b[^>]*src=["'](\.\/[^"'?]+)[^"']*["'][^>]*>/g)].map(m=>m[1]);
const css=[...h.matchAll(/<link\b[^>]*rel=["']stylesheet["'][^>]*href=["'](\.\/[^"'?]+)[^"']*["'][^>]*>/g)].map(m=>m[1]);
assert.equal(new Set(scripts).size,scripts.length,'startup must not execute same local script twice');
const bytes=scripts.reduce((n,p)=>n+fs.statSync(path.join(root,p)).size,0);
assert(scripts.length<=48,'startup local scripts <= 48, got '+scripts.length);
assert(css.length<=15,'startup stylesheets <= 15, got '+css.length);
assert(bytes<2700000,'startup JS budget < 2.7MB, got '+bytes);
assert(scripts.includes('./app/modules/flight-governance.v1.js'),'governance engine must load');
assert(scripts.some(p=>p.includes('startup-bundle-')),'safe IIFE bundles must be active');
assert(css.some(p=>p.includes('legacy-ui-bundle-')),'legacy CSS clusters must be bundled');
const sw=read('service-worker.js'),bootstrap=JSON.parse(sw.match(/const SAGS_BOOTSTRAP=(\[[^\n]+\]);/)[1]);
for(const p of [...scripts,...css])assert(bootstrap.includes(p),'offline bootstrap misses '+p);
console.log('Startup/PWA optimized: '+scripts.length+' scripts, '+css.length+' styles, '+bytes+' bytes');
