const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const repair=fs.readFileSync(__dirname+'/../repair.html','utf8');
assert.match(html,/id="sagsTestDeployment"/,'TEST deployment marker missing');
assert.match(html,/__SAGS_TEST_DEPLOYMENT=true/,'TEST deployment flag missing');
assert.doesNotMatch(html,/location\.replace\([^\n]*e-report-sags\.vercel\.app/,'TEST must never redirect to production');
assert.match(html,/id="sagsTestResetGate"/,'forced TEST reset gate missing');
assert.match(html,/__test_reset/,'forced TEST reset query missing');
assert.match(repair,/startsWith\('sags-'\)/,'repair must purge all SAGS UI caches');
assert.match(repair,/startsWith\('e-report-'\)/,'repair must purge old E-REPORT UI caches');
assert.match(repair,/\.\/index\.html/,'repair must reopen the network index explicitly');
assert.match(repair,/__repair/,'repair must use the service-worker network bypass');
console.log('TEST Pages isolation passed: no production redirect + forced stale cache reset');
