const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'app/modules/ui-preferences.v1.js'),'utf8');
const quick=fs.readFileSync(path.join(root,'app/boot/18-v173-quick-time.js'),'utf8');
const css=fs.readFileSync(path.join(root,'app/styles/new-ui-v1.css'),'utf8');
assert.match(js,/function quickDeviceKey\(\)/,'device fallback key missing');
assert.match(js,/localStorage\.setItem\(quickDeviceKey\(\),payload\)/,'device fallback persistence missing');
assert.match(js,/id="sagsQteListToggle"/,'single quick preference list toggle missing');
assert.match(js,/function setQuickCustomizeExpanded\(open\)/,'single-list expand controller missing');
assert.match(js,/setQuickCustomizeExpanded\(false\)/,'quick preference list must start collapsed');
assert.match(js,/className='sagsQteChoiceToggle'/,'expandable group heading missing');
assert.match(js,/if\(!writeHidden\(hidden\)\)/,'save must verify persistence');
assert.match(quick,/window\.qte551ToggleChecklist=function/,'FSAGS 55.1 single checklist toggle missing');
assert.match(quick,/id="qte551ChecklistBody"/,'FSAGS 55.1 checklist body missing');
assert.match(css,/V6\.4\.86 · SINGLE SHOW\/HIDE FOR QUICK-ENTRY LONG LISTS/);
assert.match(css,/\.sagsQteCustomizeOptions\[hidden\]\{display:none!important\}/);
assert.match(css,/\.qte551ChecklistBody\[hidden\]\{display:none!important\}/);
console.log('Quick-entry single-toggle preference regression checks passed');
