const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const loader=read('app/modules/stability.v6.js');
const cloud=read('app/modules/cloud-draft-sync.v2.js');
const quick=read('app/boot/18-v173-quick-time.js');
const core=read('app/modules/stability.v6-core.js');
assert.match(loader,/cloud-draft-sync\.v2\.js\?v=V2\.0/,'V2 cloud draft module must load after local recovery');
assert.match(loader,/load\(idb,\(\)=>load\(cloud\)\)/,'cloud layer must load after IndexedDB');
assert.match(cloud,/DB_NAME='sags-draft-recovery-v2'/,'dedicated immediate IndexedDB draft store missing');
assert.match(cloud,/void idbPut\(entry\);scheduleCloud\(entry\)/,'every field draft must mirror to IndexedDB then queue cloud sync');
assert.match(cloud,/roster_sessions\/.*draftRecoveryV2/,'roster-scoped cloud draft path missing');
assert.match(cloud,/Number\(remote\.atMs\)>Number\(entry\.atMs\)/,'newer remote draft conflict guard missing');
assert.match(cloud,/remote&&Number\(remote\.atMs\)>Number\(entry\.atMs\)/,'cloud write must refuse to overwrite newer remote data');
assert.doesNotMatch(cloud,/setInterval\s*\(/,'V2 draft sync must be event-driven, not a polling loop');
assert.match(quick,/sagsV61Draft\?\.read\?\.\(f\.key,"quickTime"\)/,'quick-time draft recovery read missing');
assert.match(quick,/sagsV61Draft\?\.record\?\.\(el\.dataset\.key,v,"quickTime"\)/,'quick-time input must enter draft pipeline immediately');
assert.match(quick,/sagsV61Draft\?\.forget\?\.\(c\.key,"quickTime"\)/,'saved quick-time draft must be cleared');
assert.match(core,/Nháp đã bảo vệ 3 lớp/,'operator status must expose three-layer protection');
console.log('V2.0 draft protection passed: localStorage -> IndexedDB -> conflict-safe roster RTDB backup.');
