const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),js=read('app/modules/settings.v1.js'),css=read('app/styles/new-ui-v1.css'),sw=read('service-worker.js'),pref=read('app/modules/ui-preferences.v1.js'),ver=JSON.parse(read('version.json'));
assert.equal(ver.version,'V2.1');
assert.equal(ver.build,'V2.1-20261006-FLIGHT-SEARCH-05');
assert.ok(html.includes('settings.v1.js?v='+ver.build),'Settings module must be pinned to current build');
assert.doesNotMatch(html,/settings\.v1\.css/);
assert.match(sw,/\.\/app\/modules\/settings\.v1\.js/);
assert.doesNotMatch(sw,/\.\/app\/styles\/settings\.v1\.css/);
assert.match(js,/sagsOpenSettings/);
assert.match(js,/avatarData/);
assert.match(js,/sagsDraftV2Status/);
assert.match(js,/sagsDraftV2Pull/);
assert.match(js,/sagsDraftV2Flush/);
assert.match(js,/localStorage → IndexedDB → RTDB/);
assert.doesNotMatch(js,/Chưa có API server mặc định/);
assert.match(css,/sagsCustomGreeting/);
assert.match(pref,/applyTheme\(readTheme\(\),false\)/);
assert.match(pref,/const t=readTheme\(\);/);
assert.doesNotMatch(js,/currentUserProfile\s*=/);
assert.doesNotMatch(js,/new MutationObserver\(function\(\)\{ensureMenu\(\);applyProfile\(\)\}\)/);
assert.match(js,/requestAnimationFrame\(function\(\)\{menuQueued=false;ensureMenu\(\)\}\)/);
console.log('TEST V2.1 Settings Center contract passed');
