const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),js=read('app/modules/settings.v1.js'),css=read('app/styles/new-ui-v1.css'),sw=read('service-worker.js'),pref=read('app/modules/ui-preferences.v1.js'),runtime=read('app/core/runtime.v503hf2.bundle.js'),runtimeLive=read('app/generated/runtime-1.js'),ver=JSON.parse(read('version.json'));
assert.equal(ver.version,'V2.2');
assert.equal(ver.build,'V2.2-20261006-SETTINGS-FAILSAFE-03');
assert.ok(html.includes('settings.v1.js?v='+ver.build),'Settings module must be pinned to current build');
assert.doesNotMatch(html,/settings\.v1\.css/);
assert.match(sw,/\.\/app\/modules\/settings\.v1\.js/);
assert.doesNotMatch(sw,/\.\/app\/styles\/settings\.v1\.css/);
assert.match(js,/sagsOpenSettings/);
assert.match(js,/avatarData/);
assert.match(js,/sagsDraftV2Status/);
assert.match(js,/sagsDraftV2Pull/);
assert.match(js,/sagsDraftV2Flush/);
assert.match(js,/localStorage → IndexedDB → RTDB/);
assert.doesNotMatch(js,/Chưa có API server mặc định/);
assert.match(css,/sagsCustomGreeting/);
assert.match(pref,/applyTheme\(readTheme\(\),false\)/);
assert.match(pref,/const t=readTheme\(\);/);
assert.doesNotMatch(js,/currentUserProfile\s*=/);
assert.doesNotMatch(js,/new MutationObserver\(function\(\)\{ensureMenu\(\);applyProfile\(\)\}\)/);
assert.match(js,/function observeSettingsMenu\(\)/);
assert.match(js,/observer\.observe\(body,\{childList:true,subtree:true\}\)/);
console.log('TEST V2.2 Settings Center contract passed');

assert.match(runtime,/key:\"settings\",icon:\"⚙\",label:\"Cài đặt\"/,'Settings must be native system menu item');
assert.match(js,/__SAGS_SETTINGS_CLICK_DELEGATE__/,'Settings click delegation missing');
assert.match(js,/c\.classList\.add\('show'\)/,'Settings open must show shell');

assert.match(runtimeLive,/key:\"settings\",icon:\"⚙\",label:\"Cài đặt\"/,'live runtime-1 must contain Settings menu');
assert.doesNotMatch(js,/setInterval\(/,'Settings must be event-driven, not polling');
assert.doesNotMatch(js,/observe\(document\.body,\{subtree:true/,'Settings must not observe the whole DOM');
assert.match(js,/sagsRequestNotify/,'notification permission action missing');
assert.match(js,/sagsResetDefaults/,'settings reset action missing');

assert.match(runtimeLive,/function openSettingsSafe\(\)/,'live runtime must use fail-safe Settings opener');
assert.match(runtimeLive,/data-sags-settings-failsafe/,'live runtime must be able to reload Settings module');
assert.match(runtimeLive,/forceSettingsVisible\(\)/,'live runtime must verify Settings became visible');
assert.match(js,/z-index','2147483500/,'Settings panel must force top overlay z-index');
assert.doesNotMatch(js,/stopPropagation\(\).*open\(\)/s,'Settings fallback must not block native menu click');
