(()=>{'use strict';if(window.__TVJ632)return;window.__TVJ632='V6.3.17-20260925-VZ-NA-IMMEDIATE-19';
const G='tvjgof035',P=15,W=1241,H=1755,F='tvj_gof_035',X='vz_';let form=null,tab=0,draft={},sections=[[],[],[]];
const S=v=>String(v??'').trim(),E=v=>S(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const active=()=>{try{const g=S(typeof activeFormGroup!=='undefined'?activeFormGroup:window.activeFormGroup).toLowerCase();if(g)return g===G}catch(_){}try{const sid=S(typeof activeFlightSessionId!=='undefined'?activeFlightSessionId:window.activeFlightSessionId);if(!sid||typeof readFlightSessionEnvelope!=='function')return false;const env=readFlightSessionEnvelope(sid)||{},g=S(env.activeFormGroup||env.mainForm).toLowerCase();return g===G}catch(_){return false}};
async function load(){if(form)return form;try{form=window.sagsV450GetFormRegistry?.()?.forms?.find(x=>S(x.id)===F)||null}catch(_){}if(!form){const r=await fetch('./forms/forms.registry.json?t='+Date.now(),{cache:'no-store'}),j=await r.json();form=(j.forms||[]).find(x=>S(x.id)===F)}return form}
function rt(t){t=S(t).toLowerCase();return t==='checkbox'?'check':t==='time'?'time':t==='date'?'date':t==='number'?'number':t==='textarea'?'textarea':'text'}
function bindOf(q){return S(q.bind||X+q.key)}
function accountProfile(){try{return window.__sagsGetSession?.()?.profile||window.currentUserProfile||{}}catch(_){return window.currentUserProfile||{}}}
function accountStaffId(p){let raw=S(p?.employeeCode||p?.staffCode||p?.employeeId||p?.staffId||p?.employeeNo||p?.staffNo).toUpperCase();if(!raw)return '';raw=raw.replace(/^CXR[\s_-]*/,'').replace(/\s+/g,'');return raw?'CXR-'+raw:''}
function seedAccountIdentity(doPersist=true){try{if(typeof state!=='object'||!state)return false;const p=accountProfile(),name=S(p?.name||p?.fullName||p?.displayName||p?.username),staff=accountStaffId(p);let changed=false;const put=(k,v)=>{if(v&&S(state[k])!==v){state[k]=v;changed=true}};put('acuStart_copy',name);put('Name_copy',staff);put(X+'staffName',name);put(X+'staffId',staff);for(const q of form?.fields||[]){const key=S(q.key).toUpperCase();if(key!=='NAME'&&key!=='STAFF_ID')continue;put(bindOf(q),key==='NAME'?name:staff)}if(changed&&doPersist){try{persist()}catch(_){}try{draw()}catch(_){}}return changed}catch(_){return false}}
function sectionOf(q){const x=Number(q.x)||0,y=Number(q.y)||0;if(y>=.145&&x<.5)return 0;if(y>=.145&&x>=.5&&y<.925)return 1;return 2}
function buildSections(){sections=[[],[],[]];for(const q of (form?.fields||[]).slice().sort((a,b)=>(Number(a.y)||0)-(Number(b.y)||0)||(Number(a.x)||0)-(Number(b.x)||0))){const k=bindOf(q);if(!k)continue;sections[sectionOf(q)].push({k,label:S(q.label||q.key||k),type:rt(q.type),key:S(q.key)})}}
function ensureStyle(){if(document.getElementById('tvj632QuickStyle'))return;const st=document.createElement('style');st.id='tvj632QuickStyle';st.textContent='.vz632Toggle{width:100%;min-height:38px;border:1px solid #aebdca;border-radius:8px;background:#eef3f7;color:#30465a;font:900 13px Arial}.vz632Toggle.on{background:#1f7a4c;border-color:#1f7a4c;color:#fff}.quickTimeRow.vz632Wide{grid-template-columns:1fr!important}.quickTimeRow.vz632Wide .quickTimeInput{min-height:100px;resize:vertical;line-height:1.35}.quickTimePageTitle .vz632Count{font-weight:700;opacity:.65;margin-left:6px}';document.head.appendChild(st)}
async function ensure(){const z=await load();if(!z)return;form=z;for(const q of z.fields||[]){const k=bindOf(q),o=fields.find(f=>+f.page===P&&S(f.key)===k);if(o){delete o.__formManagerCustomV463;o.__tvj632=1;continue}const a=+q.x*W,b=+q.y*H,c=Math.max(3,+q.w*W),d=Math.max(3,+q.h*H),t=rt(q.type),runtime=t==='check'?'check':t==='time'?'timeNow':t==='date'?'dateAuto':t==='number'?'number':'text';add(P,k,a,b,c,d,runtime,S(q.label||q.key),{vx:a,vy:b,vw:c,vh:d,font:+q.fontSize||16,align:S(q.align||'center'),valign:S(q.valign||'middle'),multiline:t==='textarea'||+q.rowCount>1,inputMode:(t==='number'||t==='time')?'numeric':'text',filter:t==='number'?'number':t==='time'?'time':null,leftValue:S(q.align).toLowerCase()==='left'});fields[fields.length-1].__tvj632=1}buildSections();seedAccountIdentity(true);ensureStyle();try{draw()}catch(_){}}
function toolbar(){try{document.getElementById('tvjQuickBtn')?.remove();document.getElementById('tvjQuickModal')?.remove()}catch(_){}}
function norm(v){v=S(v);if(v.toUpperCase()==='N/A')return 'N/A';let d=v.replace(/\D/g,'').slice(0,4);if(!d)return '';if(d.length===3)d='0'+d;if(d.length!==4||+d.slice(0,2)>23||+d.slice(2)>59)return null;return d.slice(0,2)+':'+d.slice(2)}
function init(){draft={};for(const a of sections)for(const f of a)draft[f.k]=f.type==='check'?!!state?.[f.k]:S(state?.[f.k])}
function now(){try{return S(nowHHMM()).replace(':','')}catch(_){const d=new Date();return String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0')}}
function cell(f){const k=E(f.k),t=f.type;if(t==='check')return '<div class="quickTimeSingleCell"><button type="button" class="vz632Toggle '+(draft[f.k]?'on':'')+'" data-vzk="'+k+'" onclick="vz632Toggle(this)">'+(draft[f.k]?'✓ ĐÃ CHỌN':'— CHƯA CHỌN')+'</button></div>';if(t==='textarea')return '<div class="quickTimeSingleCell"><textarea class="quickTimeInput" data-vzk="'+k+'" data-vzt="textarea" oninput="vz632Input(this)">'+E(draft[f.k])+'</textarea></div>';return '<div class="quickTimeSingleCell"><input class="quickTimeInput" data-vzk="'+k+'" data-vzt="'+E(t)+'" '+(t==='time'||t==='number'?'type="tel" inputmode="numeric"':'type="text"')+' value="'+E(draft[f.k])+'" placeholder="'+(t==='time'?'----':'')+'" oninput="vz632Input(this)">'+(t==='time'?'<button class="quickTimeNow" type="button" data-vzk="'+k+'" onclick="vz632Now(this)">◷</button>':'')+'</div>'}
function render(){const labs=['ĐẾN · ARRIVAL','ĐI · DEPARTURE','OTHER'],tabs=['ĐẾN','ĐI','OTHER'],body=document.getElementById('quickTimeBody');if(!body)return;document.getElementById('quickTimeTitle').textContent='NHẬP NHANH VZ · TVJ-GOF-035';document.getElementById('quickTimeFlight').textContent=[S(state?.vz_flightNumber)||'VZ',S(state?.vz_date)].filter(Boolean).join(' · ');document.getElementById('quickTimeSub').textContent=labs[tab];tabs.forEach((x,i)=>{const b=document.getElementById('qteTab'+i);if(b){b.hidden=false;b.textContent=x;b.classList.toggle('active',i===tab)}});const rows=sections[tab]||[];body.innerHTML='<div class="quickTimePageTitle">'+labs[tab]+'<span class="vz632Count">('+rows.length+' ô)</span></div><div class="quickTimeRows">'+rows.map(f=>'<div class="quickTimeRow single '+(f.type==='textarea'?'vz632Wide':'')+'"><div class="quickTimeLabel">'+E(f.label)+'</div>'+cell(f)+'</div>').join('')+'</div>';const na=document.getElementById('quickTimeNaBtn');if(na){na.style.display='';na.textContent='N/A Ô TRỐNG';na.onclick=()=>vz632FillNA()}const cl=document.getElementById('quickTimeClearBtn');if(cl){cl.style.display='';cl.textContent='BBBT';cl.onclick=()=>vz632BBBT()}}
window.vz632Input=e=>{const k=S(e.dataset.vzk),t=S(e.dataset.vzt);let v=S(e.value);const na=/^N\/?A?$/i.test(v);if(t==='time'&&!na)v=v.replace(/[^0-9:]/g,'').slice(0,5);if(t==='number'&&!na)v=v.replace(/[^0-9.]/g,'');if(na)v=v.toUpperCase();draft[k]=v;e.value=v};
window.vz632FillNA=()=>{if(!confirm('Điền N/A cho toàn bộ ô trống của TVJ-GOF-035?\n\nDữ liệu đã nhập và checkbox được giữ nguyên. NAME / STAFF ID vẫn lấy từ tài khoản đăng nhập.'))return;seedAccountIdentity(false);let n=0;for(const f of sections.flat()){if(f.type==='check'||f.key.toUpperCase()==='NAME'||f.key.toUpperCase()==='STAFF_ID')continue;const cur=S(draft[f.k]??state?.[f.k]);if(!cur){draft[f.k]='N/A';state[f.k]='N/A';n++}}seedAccountIdentity(false);try{persist()}catch(_){}try{draw()}catch(_){}render();const st=document.getElementById('quickTimeSaveStatus');if(st)st.textContent=n?'ĐÃ LƯU N/A '+n+' Ô TRỐNG':'KHÔNG CÓ Ô TRỐNG';try{if(n&&typeof showToast==='function')showToast('Đã điền và lưu N/A cho '+n+' ô trống')}catch(_){}};
window.vz632Toggle=e=>{const k=S(e.dataset.vzk);draft[k]=!draft[k];render()};
window.vz632Now=e=>{const k=S(e.dataset.vzk);draft[k]=now();render()};
function save(){seedAccountIdentity(false);const bad=[];for(const f of sections.flat()){let v=draft[f.k];if(f.type==='check'){state[f.k]=!!v;continue}v=S(v);const isNA=v.toUpperCase()==='N/A';if(f.type==='time'&&!isNA){v=norm(v);if(v===null){bad.push(f.label);continue}}if(f.type==='number'&&!isNA)v=S(v).replace(/[^0-9.]/g,'');if(isNA)v='N/A';if(v==='')delete state[f.k];else state[f.k]=v}if(bad.length){alert('Giờ chưa hợp lệ: '+[...new Set(bad)].join(', '));return false}seedAccountIdentity(false);try{persist();draw()}catch(_){}const st=document.getElementById('quickTimeSaveStatus');if(st)st.textContent='ĐÃ CẬP NHẬT';return true}
async function open(){await ensure();seedAccountIdentity(true);tab=0;init();render();const m=document.getElementById('quickTimeModal');if(m)m.style.display='flex';document.body.classList.add('sags-quicktime-open')}
window.vz632BBBT=()=>{save();try{closeQuickTimePanel()}catch(_){}setTimeout(()=>{try{selectFormGroup('bbbt')}catch(_){}},30)};
const o=window.openQuickTimePanel,g=window.qteGoPage,s=window.qteSaveCompact,v=window.quickTimeRefreshVisibility;
window.openQuickTimePanel=function(){if(active())return open();return o?.apply(this,arguments)};window.qteGoPage=function(n){if(active()){tab=Math.max(0,Math.min(2,+n||0));render();return}return g?.apply(this,arguments)};window.qteSaveCompact=function(){if(active())return save();return s?.apply(this,arguments)};window.quickTimeRefreshVisibility=function(){const r=v?.apply(this,arguments);toolbar();return r};
try{openQuickTimePanel=window.openQuickTimePanel;qteGoPage=window.qteGoPage;qteSaveCompact=window.qteSaveCompact}catch(_){}
const sf=window.showFormGroup;if(typeof sf==='function')window.showFormGroup=showFormGroup=function(){const r=sf.apply(this,arguments);setTimeout(()=>{toolbar();if(active())ensure()},0);return r};const ar=window.applyRoleUI;if(typeof ar==='function')window.applyRoleUI=applyRoleUI=function(){const r=ar.apply(this,arguments);setTimeout(toolbar,0);return r};
setTimeout(()=>{ensure();toolbar()},450);setInterval(()=>{if(active()){toolbar();if(fields.filter(f=>+f.page===P).length<100)ensure()}},1800);
})();
