/* E-REPORT SAGS V2.5 · FSAGS 208 IMAGE READER
 * OCR-first on device with Tesseract.js. Gemini is fallback only when OCR is weak.
 * Image reading fills editable draft fields only; it never sends/completes FSAGS 208.
 */
(function(root){
'use strict';
const BUILD='V2.5-20261006-FSAGS208-OCR-ZONES-07-READER',FORM='loading208';
const REGISTRY='./forms/forms.registry.json';
const TESS='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';
const S=v=>String(v??'').trim(),U=v=>S(v).toUpperCase();
let loadJob=null,workerJob=null,registryJob=null,busy=false,wrappedBase=null;
function grp(){try{return S(typeof activeFormGroup!=='undefined'?activeFormGroup:root.activeFormGroup).toLowerCase()}catch(_){return S(root.activeFormGroup).toLowerCase()}}
function st(){try{return typeof state!=='undefined'&&state&&typeof state==='object'?state:root.state}catch(_){return root.state}}
function page(){return document.getElementById('page13')}
function pageOpen(){const p=page();if(!p)return false;if(grp()===FORM)return true;try{return !p.classList.contains('hide')&&getComputedStyle(p).display!=='none'}catch(_){return !p.classList.contains('hide')}}
function readOnly(){const b=document.getElementById('kh208ReadOnlyBadge');if(!b)return false;try{return b.style.display!=='none'&&getComputedStyle(b).display!=='none'}catch(_){return b.style.display!=='none'}}
function editable(){return pageOpen()&&!readOnly()}
function stat(t){const e=document.getElementById('s208ImageReadStatus');if(e){e.textContent=t||'';e.hidden=!t}}
function prog(t,p){const b=document.getElementById('s208ImageReadBtn');if(b){b.disabled=busy||!editable();b.textContent=busy?('⏳ '+(p>=0?Math.round(p)+'%':'ĐANG ĐỌC')):'📷 ĐỌC ẢNH'}stat(t)}
function ensureUi(){
 const p=page();let bar=document.getElementById('s208ImageReadBar');
 if(!bar&&p){bar=document.createElement('div');bar.id='s208ImageReadBar';bar.setAttribute('aria-label','Công cụ đọc ảnh FSAGS 208');p.insertBefore(bar,p.firstChild)}
 let b=document.getElementById('s208ImageReadBtn');
 if(!b){b=document.createElement('button');b.id='s208ImageReadBtn';b.type='button';b.textContent='📷 ĐỌC ẢNH';b.hidden=true;b.title='Chọn ảnh phiếu 208 · OCR miễn phí đọc trước, Gemini chỉ kiểm tra lại khi cần';b.onclick=()=>{if(busy)return;if(!editable())return alert('FSAGS 208 đang ở chế độ chỉ xem.');const i=document.getElementById('s208ImageInput');if(i){i.value='';i.click()}}}
 if(bar&&b.parentElement!==bar)bar.appendChild(b);
 let i=document.getElementById('s208ImageInput');if(!i){i=document.createElement('input');i.id='s208ImageInput';i.type='file';i.accept='image/*';i.hidden=true;i.onchange=()=>{const f=i.files&&i.files[0];if(f)void readImage(f)};document.body.appendChild(i)}
 if(!document.getElementById('s208ImageReadStatus')){const e=document.createElement('div');e.id='s208ImageReadStatus';e.hidden=true;e.setAttribute('role','status');e.setAttribute('aria-live','polite');document.body.appendChild(e)}
 if(!document.getElementById('s208ImageReadStyle')){const x=document.createElement('style');x.id='s208ImageReadStyle';x.textContent='#s208ImageReadBar{position:sticky;top:calc(6px + env(safe-area-inset-top));z-index:58000;height:0;display:flex;justify-content:flex-end;align-items:flex-start;padding:0 8px;pointer-events:none;box-sizing:border-box}#s208ImageReadBtn{pointer-events:auto;min-height:34px!important;padding:6px 10px!important;margin-top:7px!important;border:1px solid #8cc9d8!important;border-radius:10px!important;background:#e8f8fb!important;color:#075e76!important;font:900 10.5px/1 Arial!important;white-space:nowrap!important;box-shadow:0 4px 14px #063b4c26!important;touch-action:manipulation}#s208ImageReadBtn.s208-show{display:inline-flex!important;align-items:center;justify-content:center}#s208ImageReadBtn:disabled{opacity:.58}#s208ImageReadStatus{position:fixed;z-index:69000;top:calc(7px + env(safe-area-inset-top));left:50%;transform:translateX(-50%);max-width:min(92vw,560px);padding:8px 12px;border:1px solid #b8dce5;border-radius:999px;background:#f5fcfe;color:#184f60;box-shadow:0 5px 18px #062b3a26;font:800 11px/1.25 system-ui,-apple-system,Segoe UI,sans-serif;text-align:center;pointer-events:none}#s208ImageReadStatus[hidden]{display:none!important}@media(max-width:600px){#s208ImageReadBar{top:calc(4px + env(safe-area-inset-top));padding-right:5px}#s208ImageReadBtn{min-height:32px!important;padding:5px 8px!important;margin-top:5px!important;font-size:10px!important}}';document.head.appendChild(x)}
 return b;
}
function sync(){const b=ensureUi(),show=pageOpen();if(!b)return;b.hidden=!show;b.disabled=busy||!editable();b.classList.toggle('s208-show',show);b.title=editable()?'Chọn ảnh phiếu 208 · OCR miễn phí đọc trước, Gemini chỉ kiểm tra lại khi cần':'FSAGS 208 đang ở chế độ chỉ xem';if(!show&&!busy)stat('')}
function patch(){const base=root.sags208SyncFormActions;if(typeof base!=='function')return false;if(base===wrappedBase||base.__sags208ImageReader)return true;const w=function(row){const r=base.apply(this,arguments);sync();return r};w.__sags208ImageReader=true;w.__base=base;wrappedBase=w;root.sags208SyncFormActions=w;return true}
function script(src){return new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.async=true;s.crossOrigin='anonymous';s.onload=ok;s.onerror=()=>{s.remove();no(Error('Không tải được OCR. Kiểm tra mạng rồi thử lại.'))};document.head.appendChild(s)})}
async function tess(){if(root.Tesseract?.createWorker)return root.Tesseract;if(!loadJob)loadJob=script(TESS).then(()=>{if(!root.Tesseract?.createWorker)throw Error('OCR chưa khởi tạo.');return root.Tesseract}).catch(e=>{loadJob=null;throw e});return loadJob}
async function worker(){if(workerJob)return workerJob;workerJob=(async()=>{const T=await tess();return await T.createWorker('eng',1,{logger:m=>{const p=Number(m?.progress);if(busy&&Number.isFinite(p))prog('OCR · '+S(m?.status||'đang xử lý'),Math.max(0,Math.min(100,p*100)))}})})().catch(e=>{workerJob=null;throw e});return workerJob}
function data(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result||''));r.onerror=()=>no(Error('Không đọc được ảnh đã chọn.'));r.readAsDataURL(file)})}
function img(url){return new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('Ảnh không hợp lệ.'));i.src=url})}
async function prep(file){const raw=await data(file),original=await img(raw);let im=original,iw=im.naturalWidth||im.width,ih=im.naturalHeight||im.height;if(iw<160||ih<160)throw Error('Ảnh quá nhỏ để đọc.');
 if(ih>iw){const r=document.createElement('canvas');r.width=ih;r.height=iw;const g=r.getContext('2d',{alpha:false});g.fillStyle='#fff';g.fillRect(0,0,r.width,r.height);g.translate(r.width/2,r.height/2);g.rotate(-Math.PI/2);g.drawImage(im,-iw/2,-ih/2);im=r;iw=r.width;ih=r.height}
 const target=1491/1055,ratio=iw/ih;let sx=0,sy=0,sw=iw,sh=ih;if(ratio>target){sw=ih*target;sx=(iw-sw)/2}else if(ratio<target){sh=iw/target;sy=(ih-sh)/2}
 const k=Math.min(1.9,2200/sw),w=Math.max(1200,Math.round(sw*k)),h=Math.round(w/target),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false,willReadFrequently:true});x.fillStyle='#fff';x.fillRect(0,0,w,h);x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(im,sx,sy,sw,sh,0,0,w,h);try{const q=x.getImageData(0,0,w,h),a=q.data;for(let n=0;n<a.length;n+=4){const y=.299*a[n]+.587*a[n+1]+.114*a[n+2],z=Math.max(0,Math.min(255,(y-128)*1.34+128));a[n]=a[n+1]=a[n+2]=z;a[n+3]=255}x.putImageData(q,0,0)}catch(_){}return c.toDataURL('image/jpeg',.94)}
function roiKey(k){return /^f208_(?:flightNo|date|acType|etd|route|uld[1-5]|priority[1-5]|awb[1-7]|totalPieces(?:[1-7])?|dest[1-7]|g[1-5](?:Pieces|Weight)_r[1-7]|start_r[1-7]|end_r[1-7]|netWeight[1-5]|tareWeight[1-5]|grossPieces[1-5]|grossWeight[1-5]|totalWeight|(?:nylon|waterproof|strap|lining)Qty)$/.test(k)}
async function roiDefs(){if(registryJob)return registryJob;registryJob=fetch(REGISTRY+'?__ocr='+encodeURIComponent(BUILD),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Không tải được tọa độ FSAGS 208');return r.json()}).then(j=>{const forms=Array.isArray(j)?j:j.forms,f=Array.isArray(forms)?forms.find(x=>x?.id==='fsags208'||x?.group===FORM):null;return (f?.fields||[]).filter(x=>roiKey(S(x.key))&&x.type!=='signature'&&x.type!=='checkbox'&&Number.isFinite(Number(x.x))&&Number.isFinite(Number(x.y))&&Number.isFinite(Number(x.w))&&Number.isFinite(Number(x.h))) }).catch(e=>{registryJob=null;console.warn('FSAGS208 OCR registry',e);return[]});return registryJob}
function roiNormalize(f,v){let x=U(v).replace(/KEY\s*\d{1,3}/g,' ').replace(/[^A-Z0-9\-\/:., ]/g,' ').replace(/\s+/g,' ').trim(),k=S(f.key);if(!x)return'';
 if(k==='f208_date')return date(x);if(k==='f208_etd'||/^f208_(?:start|end)_r/.test(k))return time(x);
 if(/^f208_awb/.test(k)){const a=awb(x);return /\d{3}-?\d{8}/.test(a.replace(/\s/g,''))?a:''}
 if(f.type==='number'||/(?:Pieces|Weight|totalPieces|totalWeight)/.test(k))return number(x);
 if(/^f208_dest/.test(k)){const m=x.match(/\b[A-Z]{3}\b/);return m?m[0]:''}
 if(k==='f208_flightNo'){const m=x.replace(/\s/g,'').match(/[A-Z0-9]{2,3}-?\d{2,5}/);return m?m[0]:''}
 if(k==='f208_route'){const m=x.match(/[A-Z]{3}(?:\s*[-\/]\s*[A-Z]{3}){1,3}/);return m?m[0].replace(/\s/g,''):''}
 if(/^f208_uld/.test(k)){const q=x.replace(/[^A-Z0-9-]/g,'');return q.length>=5&&q.length<=18?q:''}
 if(k==='f208_acType'){const q=x.replace(/[^A-Z0-9-]/g,'');return q.length>=2&&q.length<=12?q:''}
 if(/^f208_priority/.test(k)){const q=x.replace(/[^A-Z0-9-]/g,'');return q.slice(0,10)}
 if(/Qty$/.test(k))return x.slice(0,24);return x.slice(0,24)}
async function roiMosaic(url,defs){const im=await img(url),rowH=104,labelW=112,width=1040,c=document.createElement('canvas');c.width=width;c.height=Math.max(rowH,defs.length*rowH);const g=c.getContext('2d',{alpha:false,willReadFrequently:true});g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.textBaseline='middle';g.font='900 28px Arial';g.fillStyle='#111';
 defs.forEach((f,i)=>{const y=i*rowH,padX=Math.max(2,Number(f.w)*im.width*.12),padY=Math.max(2,Number(f.h)*im.height*.24),sx=Math.max(0,Number(f.x)*im.width-padX),sy=Math.max(0,Number(f.y)*im.height-padY),sw=Math.min(im.width-sx,Number(f.w)*im.width+padX*2),sh=Math.min(im.height-sy,Number(f.h)*im.height+padY*2);g.fillStyle='#111';g.fillText('KEY'+String(i+1).padStart(3,'0'),8,y+rowH/2);g.strokeStyle='#ddd';g.beginPath();g.moveTo(0,y+rowH-1);g.lineTo(width,y+rowH-1);g.stroke();const maxW=width-labelW-16,scale=Math.min(maxW/sw,(rowH-14)/sh),dw=Math.max(1,sw*scale),dh=Math.max(1,sh*scale);g.drawImage(im,sx,sy,sw,sh,labelW,y+(rowH-dh)/2,dw,dh)});
 try{const q=g.getImageData(labelW,0,c.width-labelW,c.height),a=q.data;for(let n=0;n<a.length;n+=4){const y=.299*a[n]+.587*a[n+1]+.114*a[n+2],z=y>205?255:(y<105?0:Math.max(0,Math.min(255,(y-155)*1.75+155)));a[n]=a[n+1]=a[n+2]=z;a[n+3]=255}g.putImageData(q,labelW,0)}catch(_){}return c.toDataURL('image/png')}
function roiParse(text,defs){const out={},raw=String(text||'');const re=/KEY\s*0*(\d{1,3})\s*([\s\S]*?)(?=KEY\s*0*\d{1,3}|$)/gi;let m;while((m=re.exec(raw))){const idx=Number(m[1])-1,f=defs[idx];if(!f)continue;const v=roiNormalize(f,m[2]);if(v!=='')out[f.key]=v}return out}
async function roiPass(url,w){const defs=await roiDefs();if(!defs.length)return{fields:{},count:0,raw:'',confidence:0};const fields={},logs=[],scores=[];const size=24,total=Math.ceil(defs.length/size);for(let i=0;i<defs.length;i+=size){const part=defs.slice(i,i+size);prog('OCR 2/2 · đọc đúng từng ô 208 ('+(Math.floor(i/size)+1)+'/'+total+')',Math.min(96,45+(i/defs.length)*48));const mosaic=await roiMosaic(url,part);try{await w.setParameters({tessedit_pageseg_mode:'6',preserve_interword_spaces:'1',tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789KEY-/:.,'})}catch(_){}const r=await w.recognize(mosaic),d=r?.data||{},got=roiParse(d.text,part);Object.assign(fields,got);logs.push(S(d.text));if(Number.isFinite(Number(d.confidence)))scores.push(Number(d.confidence))}try{await w.setParameters({tessedit_char_whitelist:''})}catch(_){}return{fields,count:Object.keys(fields).length,raw:logs.join('\n'),confidence:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0}}
function clean(v){return U(v).replace(/[|]/g,' ').replace(/\s+/g,' ').trim()}
function number(v){const m=S(v).replace(/[, ]/g,'').match(/\d+(?:\.\d+)?/);return m?m[0]:''}
function time(v){const m=S(v).match(/(\d{1,2})[:.](\d{2})/);return m?m[1].padStart(2,'0')+':'+m[2]:''}
function date(v){const m=S(v).match(/(\d{1,2})[\/.\-](\d{1,2})[\/.\-](\d{2,4})/);return m?(m[3].length===2?'20'+m[3]:m[3])+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0'):''}
function awb(v){const d=S(v).replace(/[^\d]/g,'');return d.length===11?d.slice(0,3)+'-'+d.slice(3):S(v)}
function put(o,k,v){if(v!==''&&v!==undefined&&v!==null)o[k]=v}
function parse(text,confidence){
 const lines=String(text||'').split(/\r?\n/).map(clean).filter(Boolean),all=' '+lines.join(' ')+' ',f={};let m;
 m=all.match(/(?:FLIGHT(?:\s*NO)?|FLT(?:\s*NO)?)\s*[:#-]?\s*([A-Z0-9]{2,3}\s*[- ]?\s*\d{2,5})/i);if(m)put(f,'f208_flightNo',m[1].replace(/\s+/g,''));
 m=all.match(/\bDATE\s*[:#-]?\s*(\d{1,2}[\/.\-]\d{1,2}[\/.\-]\d{2,4})/i);if(m)put(f,'f208_date',date(m[1]));
 m=all.match(/(?:A\/C|AC)\s*TYPE\s*[:#-]?\s*([A-Z0-9-]{3,10})/i);if(m)put(f,'f208_acType',m[1]);
 m=all.match(/\bETD\s*[:#-]?\s*(\d{1,2}[:.]\d{2})/i);if(m)put(f,'f208_etd',time(m[1]));
 m=all.match(/\bROUTE\s*[:#-]?\s*([A-Z]{3}(?:\s*[-/]\s*[A-Z]{3}){1,3})/i);if(m)put(f,'f208_route',m[1].replace(/\s+/g,''));
 const u=[];for(const line of lines)for(const x of line.match(/\b(?:AKE|AKH|PMC|PAG|PLA|RKN|DPE|ALF)[A-Z0-9-]{3,12}\b/g)||[])if(!u.includes(x))u.push(x);u.slice(0,5).forEach((x,i)=>put(f,'f208_uld'+(i+1),x));
 let rows=0;for(const line of lines){const a=line.match(/\b(\d{3}[- ]?\d{8})\b/);if(!a||rows>=7)continue;rows++;const after=line.slice(line.indexOf(a[0])+a[0].length),nums=after.match(/\b\d+(?:\.\d+)?\b/g)||[],dest=(after.match(/\b[A-Z]{3}\b/g)||[])[0]||'';put(f,'f208_awb'+rows,awb(a[1]));if(nums[0])put(f,'f208_totalPieces'+rows,number(nums[0]));put(f,'f208_dest'+rows,dest);let p=1;for(let g=1;g<=5;g++){if(nums[p])put(f,'f208_g'+g+'Pieces_r'+rows,number(nums[p++]));if(nums[p])put(f,'f208_g'+g+'Weight_r'+rows,number(nums[p++]))}const ts=after.match(/\b\d{1,2}[:.]\d{2}\b/g)||[];if(ts[0])put(f,'f208_start_r'+rows,time(ts[0]));if(ts[1])put(f,'f208_end_r'+rows,time(ts[1]))}
 for(const line of lines)if(/\bTOTAL\b/.test(line)){const ns=line.match(/\b\d+(?:\.\d+)?\b/g)||[];if(ns.length>=2){put(f,'f208_totalPieces',number(ns[ns.length-2]));put(f,'f208_totalWeight',number(ns[ns.length-1]))}}
 const tick=(w,k)=>{if(new RegExp('(?:[Xx✓✔☑]\\s*'+w+'|'+w+'\\s*[Xx✓✔☑])','i').test(all))f[k]=true};tick('GOOD','f208_condGood');tick('OLD','f208_condOld');tick('DIRTY','f208_condDirty');tick('WET','f208_condWet');
 const count=Object.keys(f).length,anchors=['AWB','ULD','PIEC','WEIGHT','FLIGHT'].filter(x=>all.includes(x)).length;let quality=Math.round(Math.max(0,Math.min(100,Number(confidence)||0))*.58+Math.min(26,count*2)+anchors*3+(rows?8:0));return {fields:f,quality:Math.min(100,quality),count,rows,raw:String(text||'').slice(0,12000)};
}
function valid(k){return /^f208_(?:flightNo|date|acType|etd|route|cond(?:Good|Old|Basket|Dirty|Wet|Other)|uld[1-5]|priority[1-5]|awb[1-7]|totalPieces(?:[1-7])?|dest[1-7]|g[1-5](?:Pieces|Weight)_r[1-7]|start_r[1-7]|end_r[1-7]|netWeight[1-5]|tareWeight[1-5]|grossPieces[1-5]|grossWeight[1-5]|totalWeight|nylon(?:Sags|Airline|Qty)|waterproof(?:Sags|Airline|Qty)|strap(?:Sags|Airline|Qty)|lining(?:Sags|Airline|Qty)|remark(?:_copy){0,4})$/.test(k)}
function aiFields(ai){const out={},src=ai?.fields&&typeof ai.fields==='object'?ai.fields:{};for(const[k,v]of Object.entries(src)){if(!valid(k))continue;if(typeof v==='boolean')out[k]=v;else if(v!==null&&v!==undefined&&S(v)!=='')out[k]=S(v)}return out}
async function gemini(url,ocr){prog('OCR chưa đủ chắc chắn · Gemini đang kiểm tra lại',-1);try{await root.sagsLoadAiFeature?.();if(typeof root.sagsAi208ReadImage!=='function')throw Error('Gemini chưa sẵn sàng.');return await root.sagsAi208ReadImage(url,{text:ocr.raw,quality:ocr.quality,fields:ocr.fields})}catch(e){console.warn('FSAGS208 Gemini fallback',e);return {error:S(e?.message||e)}}}
function blank(v){return v===undefined||v===null||S(v)===''||v===false}
function apply(fields){const x=st();if(!x)throw Error('Không tìm thấy dữ liệu FSAGS 208 đang mở.');let applied=0,kept=0;for(const[k,v]of Object.entries(fields||{})){if(!valid(k))continue;if(!blank(x[k])){kept++;continue}if(typeof v==='boolean')x[k]=v;else if(v!==''&&v!==null&&v!==undefined)x[k]=S(v);else continue;applied++}if(applied){try{root.draw?.()}catch(_){}try{root.saveKH208Local?.()}catch(_){}try{root.persist?.()}catch(_){}try{root.dispatchEvent(new CustomEvent('sags:fsags208-image-imported',{detail:{applied,kept,atMs:Date.now()}}))}catch(_){}}return {applied,kept}}
async function readImage(file){
 if(busy)return;if(!editable())return alert('Chỉ đọc ảnh khi FSAGS 208 đang mở ở chế độ chỉnh sửa.');if(!/^image\//i.test(S(file?.type)))return alert('Vui lòng chọn một ảnh.');
 busy=true;sync();prog('Chuẩn bị ảnh…',0);
 try{const url=await prep(file);prog('OCR 1/2 · đọc toàn phiếu trên thiết bị…',4);const w=await worker(),r=await w.recognize(url,{rotateAuto:true}),d=r?.data||{},ocr=parse(d.text,Number(d.confidence)||0);const roi=await roiPass(url,w);let fields={...ocr.fields,...roi.fields},method=roi.count?'OCR 2 LỚP':'OCR',ai=null,combined={...ocr,fields,count:Object.keys(fields).length,quality:Math.min(100,ocr.quality+Math.min(24,Math.round(roi.count*.32))),raw:ocr.raw+'\n[OCR VÙNG 208]\n'+roi.raw};const needs=combined.quality<84||combined.count<12||(ocr.rows===0&&!Object.keys(fields).some(k=>/^f208_uld/.test(k)));if(needs){ai=await gemini(url,combined);if(!ai?.error){fields={...fields,...aiFields(ai)};method=(roi.count?'OCR 2 LỚP':'OCR')+' + GEMINI'}}const res=apply(fields),note=ai?.error?' · Gemini không dùng được, giữ OCR':'';if(!res.applied)throw Error('Không nhận diện được dữ liệu 208 đủ tin cậy.'+note);const msg='✓ '+method+': đã điền '+res.applied+' ô'+(res.kept?' · giữ nguyên '+res.kept+' ô đã có dữ liệu':'')+note;stat(msg);try{root.showToast?.(msg)}catch(_){}try{root.writeUserActivity?.('ĐỌC ẢNH FSAGS 208',method+' · '+res.applied+' ô')}catch(_){}setTimeout(()=>{if(!busy)stat('')},5500)}catch(e){console.error('FSAGS 208 image reader',e);alert('Không đọc được ảnh: '+S(e?.message||e));stat('Không đọc được ảnh · dữ liệu cũ vẫn giữ nguyên.')}finally{busy=false;prog('',-1);sync()}
}
root.sags208ReadImage=()=>document.getElementById('s208ImageReadBtn')?.click();
function install(){ensureUi();patch();sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
root.addEventListener('pageshow',()=>setTimeout(install,80),{passive:true});root.addEventListener('sags:ui-ready',install);root.addEventListener('sags:personal-roster-updated',()=>setTimeout(install,80));document.addEventListener('click',e=>{if(e.target?.closest?.('button,[role="button"],a,.v157MenuItem,[data-v6494-key]')){setTimeout(sync,0);setTimeout(sync,90);setTimeout(sync,260)}},true);setTimeout(install,450);setTimeout(install,1500);
root.addEventListener('beforeunload',()=>{try{workerJob?.then(w=>w?.terminate?.())}catch(_){}},{once:true});
root.__SAGS_FSAGS208_IMAGE_READER={build:BUILD,parseOcr:parse,roiPass,aiFields,validKey:valid};
})(window);
