/* E-REPORT SAGS V4.8.10B-HF4 — employees may SELF-ACCEPT released/completed 42.1 + 55.1.
 * A/B do not need a manager/AD; C selects the flight and confirms BOTH forms.
 * Existing assignment ID, session envelope, completionEnvelope and workspace are preserved.
 * This client checks eligibility, but Firebase RTDB rules MUST enforce authorization too.
 */
(function(root){
'use strict';
if(root.__SAGS_HF4_SELF_HANDOVER)return;
root.__SAGS_HF4_SELF_HANDOVER=true;
const S=x=>String(x??'').trim(),U=x=>S(x).toUpperCase(),safe=x=>S(x).replace(/[.#$\[\]\/]/g,'_');
const esc=x=>S(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>{try{return typeof root.normalizePersonalUsername==='function'?root.normalizePersonalUsername(x):U(x).replace(/\s+/g,'').replace(/[^A-Z0-9._-]/g,'_').slice(0,40)}catch(_){return U(x).replace(/\s+/g,'').replace(/[^A-Z0-9._-]/g,'_').slice(0,40)}};
const session=()=>{try{return root.__sagsGetSession?.()||{role:root.currentRole,profile:root.currentUserProfile}}catch(_){return {role:root.currentRole,profile:root.currentUserProfile}}};
const role=()=>U(session().role||session().profile?.role),me=()=>norm(session().profile?.username);
const db=p=>{if(typeof root.sagsV470Ref!=='function')throw Error('Chưa kết nối Firebase.');return root.sagsV470Ref(p)};
const day=()=>S(document.getElementById('fwcDate')?.value)||S(sessionStorage.getItem('sagsV36FwcDate'))||new Date().toISOString().slice(0,10);
const isDate=x=>/^\d{4}-\d{2}-\d{2}$/.test(x);
const form=x=>{const v=U(x?.formGroup);return v==='FSAGS421'?'42.1':v==='FSAGS551'?'55.1':''};
const dh=x=>{const source=U(x?.sourceColumn),rk=U(x?.roleKey);return !!form(x)&&(source.includes('GRND_COR')||source.includes('GRND_LD')||['COR','LD','BOTH'].includes(rk)||!source&&!rk)};
const flightId=x=>S(x?.flightId||x?.flightRaw||x?.flightName);
const flightTokens=x=>[...new Set([S(x?.flightId),S(x?.flightRaw),S(x?.flightName),S(x?.arrFlight),S(x?.depFlight)].flatMap(t=>[...U(t).matchAll(/[A-Z0-9]{2,3}\s*\d{1,5}/g)].map(m=>m[0].replace(/[^A-Z0-9]/g,''))))];
const matchFlight=(x,q)=>{q=U(q).replace(/[^A-Z0-9]/g,'');return q.length>=3&&(flightTokens(x).includes(q)||U(flightId(x)).replace(/[^A-Z0-9]/g,'')===q)};
const done=st=>{const x=U(st?.taskStatusV333||st?.taskStatus||st?.workPartStatus||st?.claimStatus);return ['COMPLETED','PART_COMPLETED','HANDED_OVER','DONE','FINISHED'].includes(x)||Number(st?.completedAtMs||0)>0||!!st?.completedPushback};
const released=st=>st?.selfHandoverReleased===true;
const canceled=st=>st?.skippedNoEform===true||st?.autoSkippedByNextUser===true||U(st?.claimStatus)==='SKIPPED';
const eligible=(x,st)=>dh(x)&&x.active!==false&&x.duplicateInactive!==true&&!canceled(st)&&done(st);
let ui=null,busy=false,catalogCache=null;
async function profile(){const s=session(),p=s.profile||{};if(role()!=='DH'||!me()||p.active===false)throw Error('Chỉ nhân viên Điều hành đang đăng nhập được tự nhận 42.1 / 55.1.');return p;}
async function catalog(){if(catalogCache)return catalogCache;const list=await root.v466GetUserCatalog?.(false);catalogCache=Array.isArray(list)?list:[];return catalogCache;}
async function ownerEligible(owner){const users=await catalog(),cur=users.find(p=>norm(p.username)===me()),old=users.find(p=>norm(p.username)===owner);if(cur&&cur.active===false)throw Error('Tài khoản người nhận đã bị vô hiệu hóa.');if(old){const p=session().profile||cur||{},a=U(p.systemDepartment||p.departmentCode||p.department),b=U(old.systemDepartment||old.departmentCode||old.department);if(a&&b&&a!==b)throw Error('Người nhận không cùng bộ phận với người giao.');}return true;}
async function readStatus(aid){const keys=['taskStatusV333','taskStatus','workPartStatus','claimStatus','completedAtMs','completedPushback','selfHandoverReleased','skippedNoEform','autoSkippedByNextUser','ownerUser','claimedBy','coClaimedBy','updatedAtMs'];const v={};await Promise.all(keys.map(async k=>{const snap=await db(`roster_sessions/${safe(aid)}/${k}`).once('value');v[k]=snap.val()}));return v;}
async function readItem(date,aid){const snap=await db(`roster_manifests/${safe(date)}/items/${safe(aid)}`).once('value');return snap.val()||null;}
async function listEligible(date,query){await profile();if(!isDate(date))throw Error('Ngày khai thác không hợp lệ.');if(!S(query)||U(query).replace(/[^A-Z0-9]/g,'').length<3)throw Error('Nhập số chuyến đến hoặc đi, ví dụ VJ5063.');const man=(await db(`roster_manifests/${safe(date)}/items`).once('value')).val()||{};const matches=Object.entries(man).filter(([id,x])=>x&&dh(x)&&x.active!==false&&norm(x.user||x.targetUser)!==me()&&matchFlight(x,query));if(!matches.length)return [];
 const entries=await Promise.all(matches.map(async ([id,x])=>{const item={...x,assignmentId:S(x.assignmentId||id)};const st=await readStatus(item.assignmentId);return {item,st}}));return entries.filter(e=>eligible(e.item,e.st));}
async function reserve(date,aid,target,key,old){const ref=db(`roster_sessions/${safe(aid)}/selfPickupLock`);if(typeof ref.transaction!=='function')throw Error('Không có transaction Firebase; không thể nhận an toàn.');const now=Date.now();const result=await ref.transaction(cur=>{if(cur?.status==='ACCEPTED'&&norm(cur.by)!==old)return;if(cur?.status==='RESERVED'&&Number(cur.expiresAtMs||0)>now&&S(cur.key)!==key)return;return {status:'RESERVED',by:target,key,atMs:now,expiresAtMs:now+60000} });if(!result?.committed)throw Error('Có người khác đang nhận công việc này. Hãy tải lại danh sách.');return ref;}
async function unlock(ref,key){try{await ref?.transaction(cur=>cur?.status==='RESERVED'&&cur?.key===key?null:undefined)}catch(e){console.warn('HF4 unlock',e?.message||e)}}
async function audit(event,detail){try{await db('ops_audit_v331').push({schema:1,event,clientAtMs:Date.now(),actor:{username:me(),role:role()},detail})}catch(e){console.info('HF4 audit',e?.message||e)}}
async function accept(ids,date,query){await profile();if(busy)throw Error('Đang có thao tác nhận ca.');ids=[...new Set((ids||[]).map(S).filter(Boolean))];if(!ids.length)throw Error('Chưa chọn công việc để nhận.');if(!isDate(date))throw Error('Ngày khai thác không hợp lệ.');const target=me(),key=target+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),locks=[];busy=true;
 try{
  const candidates=await listEligible(date,query),chosen=ids.map(id=>candidates.find(e=>S(e.item.assignmentId)===id));if(chosen.some(x=>!x))throw Error('Công việc đã đổi trạng thái hoặc không thuộc chuyến đang chọn.');if(new Set(chosen.map(x=>flightId(x.item))).size!==1)throw Error('Chỉ nhận nhiều việc trên cùng một chuyến.');
  for(const {item} of chosen)await ownerEligible(norm(item.user||item.targetUser));
  if(!root.confirm(`TỰ NHẬN VIỆC\n\n${chosen.map(({item})=>`${form(item)} · ${norm(item.user||item.targetUser)} → ${target}`).join('\n')}\n\nGiữ nguyên dữ liệu từng mẫu; C tiếp tục trên 42.1 và 55.1 riêng biệt. Xác nhận nhận?`))return false;
  for(const {item} of chosen){const aid=S(item.assignmentId);locks.push([await reserve(date,aid,target,key,norm(item.user||item.targetUser)),aid]);}
  // Re-read authoritative owner and eligibility AFTER acquiring locks.
  const latest=await Promise.all(chosen.map(async({item})=>({item:await readItem(date,item.assignmentId),st:await readStatus(item.assignmentId),aid:S(item.assignmentId),expected: norm(item.user||item.targetUser)})));
  for(const row of latest)if(!row.item||!eligible(row.item,row.st)||norm(row.item.user||row.item.targetUser)!==row.expected||norm(row.item.user||row.item.targetUser)===target)throw Error('Một phần việc đã đổi người/trạng thái; chưa chuyển bất kỳ công việc nào.');
  const t=Date.now(),patch={};for(const {item,st,aid,expected:old} of latest){const src=`roster_sessions/${safe(aid)}`,fid=flightId(item),prevCompleted=done(st);let oldMail={};try{oldMail=(await db(`roster_mail/${safe(old)}/items/${safe(aid)}`).once('value')).val()||{}}catch(_){}const original=norm(item.originalUser||item.originalTargetUser||oldMail.originalTargetUser||old)||old;
   const next={...oldMail,...item,assignmentId:aid,opDate:date,user:target,targetUser:target,originalUser:original,originalTargetUser:original,manualOverride:true,reassignedFrom:old,reassignedAtMs:t,reassignedBy:target,handoverAcceptedAtMs:t,claimStatus:'UNCLAIMED',workPartStatus:'UNCLAIMED',taskStatusV333:'UNCLAIMED',taskAvailabilityV333:'READY',active:true,updatedAtMs:t};
   patch[`roster_mail/${safe(old)}/items/${safe(aid)}`]=null;patch[`roster_mail/${safe(target)}/items/${safe(aid)}`]=next;
   patch[`roster_revocations/${safe(old)}/items/${safe(aid)}`]={assignmentId:aid,reason:'SELF_HANDOVER_ACCEPTED',toUser:target,atMs:t,by:target};patch[`roster_revocations/${safe(target)}/items/${safe(aid)}`]=null;
   patch[`roster_manifests/${safe(date)}/items/${safe(aid)}`]={...item,user:target,targetUser:target,originalUser:original,manualOverride:true,reassignedFrom:old,reassignedAtMs:t,lastReassignedAtMs:t,lastReassignedBy:target,selfHandoverReceivedAtMs:t};
   Object.assign(patch,{[`${src}/ownerUser`]:target,[`${src}/reassignedFrom`]:old,[`${src}/reassignedAtMs`]:t,[`${src}/reassignedBy`]:target,[`${src}/claimedBy`]:null,[`${src}/claimedAtMs`]:null,[`${src}/coClaimedBy`]:null,[`${src}/coClaimedAssignmentId`]:null,[`${src}/claimStatus`]:'UNCLAIMED',[`${src}/workPartStatus`]:'UNCLAIMED',[`${src}/taskStatusV333`]:'UNCLAIMED',[`${src}/taskAvailabilityV333`]:'READY',[`${src}/handoverReady`]:true,[`${src}/workPartReady`]:true,[`${src}/selfHandoverReleased`]:false,[`${src}/selfHandoverAcceptedBy`]:target,[`${src}/selfHandoverAcceptedAtMs`]:t,[`${src}/selfPickupLock`]:{status:'ACCEPTED',by:target,key,atMs:t},[`${src}/updatedAtMs`]:t});
   if(prevCompleted){patch[`${src}/previousCompletedAtMs`]=Number(st.completedAtMs||0)||t;patch[`${src}/pushbackEditReopened`]=true;patch[`${src}/completedAtMs`]=null;patch[`${src}/completedBy`]=null;patch[`${src}/completedPushback`]=null;patch[`${src}/skippedNoEform`]=false;patch[`${src}/autoSkippedByNextUser`]=false;}
   if(fid){const base=`flight_records/${safe(date)}/${safe(fid)}`,ev=`SELF_${t}_${safe(aid)}`;patch[`${base}/assignments/${safe(aid)}/user`]=target;patch[`${base}/assignments/${safe(aid)}/originalUser`]=original;patch[`${base}/assignments/${safe(aid)}/active`]=true;patch[`${base}/taskStatus/${safe(aid)}/ownerUser`]=target;patch[`${base}/taskStatus/${safe(aid)}/status`]='UNCLAIMED';patch[`${base}/taskStatus/${safe(aid)}/availability`]='READY';patch[`${base}/taskStatus/${safe(aid)}/updatedAtMs`]=t;patch[`${base}/assignmentOverrideHistory/${safe(ev)}`]={eventId:ev,type:'SELF_HANDOVER_ACCEPTED',assignmentId:aid,fromUser:old,toUser:target,formGroup:S(item.formGroup),atMs:t,by:target,previouslyCompleted:prevCompleted};patch[`${base}/taskClaims/${safe(old)}/${safe(aid)}/status`]='REASSIGNED';patch[`${base}/taskClaims/${safe(old)}/${safe(aid)}/reassignedTo`]=target;patch[`${base}/taskClaims/${safe(old)}/${safe(aid)}/reassignedAtMs`]=t;}
  }
  // Ownership of BOTH forms changes in ONE RTDB multi-location write.
  // Never copy, merge, delete or mutate envelope/state/completionEnvelope/workspace.
  await db('').update(patch);
  root.sagsV477InvalidateQueueStatus?.();await audit('SELF_HANDOVER_ACCEPTED',{date,flightId:flightId(latest[0].item),assignmentIds:ids,fromUsers:latest.map(x=>x.expected)});
  alert(`✓ ${target} đã tự nhận ${latest.length} phần việc. Mở MY FLIGHT để xem riêng 42.1 và 55.1.`);
  try{await root.flightWorkspaceRefresh?.()}catch(_){}return true;
 }finally{for(const [ref] of locks)await unlock(ref,key);busy=false;}
}
root.sagsHF4ListEligible=listEligible;root.sagsHF4Release=async()=>{throw Error('Đã bỏ bàn giao. Chỉ tự nhận công việc đã HOÀN TẤT.');};root.sagsHF4SelfAccept=accept;
function style(){if(document.getElementById('sagsHF4SelfCss'))return;const s=document.createElement('style');s.id='sagsHF4SelfCss';s.textContent=`.hf4Open{border:1px solid #90b6de;background:#e8f3ff;color:#064b87;border-radius:9px;padding:9px 10px;font:900 12px Arial;min-height:41px;cursor:pointer}.hf4Release{margin:3px 4px 6px 0;border:1px solid #daa76f;background:#fff2e0;color:#884500;border-radius:9px;padding:8px;font:800 11px Arial;min-height:37px;cursor:pointer}.hf4Modal{position:fixed;inset:0;background:#081d38a8;z-index:20050;display:none;align-items:center;justify-content:center;padding:12px;box-sizing:border-box}.hf4Modal.open{display:flex}.hf4Panel{box-sizing:border-box;width:min(96vw,680px);max-height:92dvh;overflow:auto;background:#fff;border-radius:16px;padding:15px;font:13px/1.4 Arial;color:#183654}.hf4Head{display:flex;gap:8px;justify-content:space-between;align-items:center}.hf4Head h3{margin:0;font:900 17px Arial;color:#16447a}.hf4Row{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0}.hf4Row input{box-sizing:border-box;flex:1 1 130px;min-width:0;padding:10px;border:1px solid #9fb6ce;border-radius:9px;font:14px Arial}.hf4Row button,.hf4Done{border:0;background:#245499;color:#fff;border-radius:9px;padding:10px;font:900 12px Arial;min-height:42px;cursor:pointer}.hf4Done{width:100%;margin-top:10px}.hf4Row button:disabled,.hf4Done:disabled{opacity:.5}.hf4Item{display:flex;gap:10px;align-items:center;padding:11px;margin:7px 0;border:1px solid #d4e0ed;border-radius:11px;background:#f8fbff}.hf4Item input{width:21px;height:21px;flex-shrink:0}.hf4Item b{display:block;font:900 13px Arial;color:#153b6c}.hf4Item small{display:block;color:#53667c;margin-top:3px}.hf4Note{font:11px/1.45 Arial;color:#5b6f83;margin:8px 0}.hf4Error{color:#a32222;font-weight:bold}.hf4Status{min-height:20px;color:#315475;font-weight:700}@media(max-width:490px){.hf4Panel{max-height:96dvh;padding:11px}.hf4Row button{width:100%}}`;document.head.appendChild(s)}
function ensureModal(){style();let m=document.getElementById('hf4SelfModal');if(m)return m;m=document.createElement('div');m.id='hf4SelfModal';m.className='hf4Modal';m.innerHTML='<div class="hf4Panel" role="dialog" aria-modal="true" aria-label="Tự nhận công việc"><div class="hf4Head"><h3>⇄ TỰ NHẬN VIỆC</h3><button class="hf4Open" type="button" data-hf4-close>ĐÓNG</button></div><p class="hf4Note">Không cần AD duyệt. Chỉ hiện phần việc 42.1 / 55.1 đã HOÀN TẤT; người nhận tự xác nhận. Dữ liệu hai mẫu giữ riêng.</p><div class="hf4Row"><input type="date" id="hf4Date"><input id="hf4Flight" placeholder="Số chuyến: VJ5063" autocomplete="off"><button type="button" id="hf4Search">TÌM CÔNG VIỆC</button></div><div id="hf4Status" class="hf4Status"></div><div id="hf4List"></div><button type="button" id="hf4Accept" class="hf4Done" disabled>NHẬN CÁC VIỆC ĐÃ CHỌN</button></div>';document.body.appendChild(m);m.querySelector('[data-hf4-close]').onclick=()=>m.classList.remove('open');m.querySelector('#hf4Search').onclick=()=>void searchUI();m.querySelector('#hf4Flight').addEventListener('keydown',e=>{if(e.key==='Enter')void searchUI()});m.querySelector('#hf4Accept').onclick=()=>void acceptUI();m.querySelector('#hf4List').addEventListener('change',()=>m.querySelector('#hf4Accept').disabled=!m.querySelector('#hf4List input:checked'));return m}
async function searchUI(){const m=ensureModal(),date=S(m.querySelector('#hf4Date').value),q=S(m.querySelector('#hf4Flight').value),s=m.querySelector('#hf4Status'),list=m.querySelector('#hf4List'),go=m.querySelector('#hf4Search');go.disabled=true;m.querySelector('#hf4Accept').disabled=true;s.textContent='Đang kiểm tra phần việc đủ điều kiện...';list.innerHTML='';try{const data=await listEligible(date,q);if(!data.length){s.textContent='Chưa có 42.1 / 55.1 đã hoàn tất trên chuyến này.';return}s.textContent=`Có ${data.length} phần việc có thể tự nhận.`;list.innerHTML=data.map(({item,st})=>`<label class="hf4Item"><input type="checkbox" data-aid="${esc(item.assignmentId)}" checked><span><b>${esc(flightId(item))} · FSAGS ${form(item)}</b><small>${esc(norm(item.user||item.targetUser))} · ĐÃ HOÀN TẤT · dữ liệu giữ nguyên</small></span></label>`).join('');m.querySelector('#hf4Accept').disabled=false}catch(e){s.textContent='Không tìm được công việc: '+S(e?.message||e);s.classList.add('hf4Error')}finally{go.disabled=false}}
async function acceptUI(){const m=ensureModal(),btn=m.querySelector('#hf4Accept'),ids=[...m.querySelectorAll('#hf4List input:checked')].map(x=>S(x.dataset.aid)),s=m.querySelector('#hf4Status');btn.disabled=true;try{const ok=await accept(ids,S(m.querySelector('#hf4Date').value),S(m.querySelector('#hf4Flight').value));if(ok){m.classList.remove('open');await root.flightWorkspaceOpenList?.(S(m.querySelector('#hf4Date').value));}else btn.disabled=false}catch(e){console.error('HF4 self pickup',e);s.textContent='Không tự nhận được: '+S(e?.message||e);s.classList.add('hf4Error');btn.disabled=false}}
function openUI(){try{profile();const m=ensureModal();m.querySelector('#hf4Date').value=day();m.classList.add('open');m.querySelector('#hf4Status').textContent='Nhập số chuyến và bấm TÌM CÔNG VIỆC.';m.querySelector('#hf4Status').classList.remove('hf4Error');m.querySelector('#hf4List').innerHTML='';m.querySelector('#hf4Accept').disabled=true}catch(e){alert(S(e?.message||e))}}
root.sagsHF4OpenSelfHandover=openUI;
function enhance(){
  if(role()!=='DH'||!me())return;
  const tools=document.querySelector('#fwcModal.show .fwcTools');if(!tools)return;
  style();
  if(!tools.querySelector('#hf4OpenBtn')){
    const b=document.createElement('button');b.id='hf4OpenBtn';b.type='button';b.className='hf4Open';
    b.textContent='⇄ TỰ NHẬN VIỆC';b.onclick=openUI;tools.appendChild(b);
  }
  // Remove only obsolete handover buttons; never erase form data or assignment records.
  document.querySelectorAll('.hf4Release').forEach(el=>el.remove());
}
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;Promise.resolve().then(()=>{scheduled=false;enhance()})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
})(typeof window!=='undefined'?window:globalThis);
