/* E-REPORT SAGS V2.2 · Settings Center
 * Personal display profile only. Never mutates roster/form/legal identity.
 */
(function(w){
'use strict';
var BUILD='V2.2-20261006-AUDIT-PERF-02';
if(w.__SAGS_SETTINGS_CENTER__===BUILD)return;
w.__SAGS_SETTINGS_CENTER__=BUILD;
var D={schema:1,displayName:'',avatarData:'',appearance:'dark',fontScale:'normal',compactMode:false,soundEnabled:true,vibrationEnabled:true,notifications:{device:true,assignment:true,handover:true,returned:true,roster:true,update:true},autoSync:true,warnUnsynced:true,autoLockMinutes:0,updatedAtMs:0};
var P={},uidKey='',cloudState='Chỉ lưu trên thiết bị',cloudAt=0,saveTimer=0,lockTimer=0,mediaBase=null,vibrateBase=null,observer=null;
var $=function(id){return document.getElementById(id)},S=function(v){return String(v==null?'':v).trim()},U=function(v){return S(v).toUpperCase()};
function clone(v){try{return JSON.parse(JSON.stringify(v))}catch(e){return Object.assign({},v)}}
function merge(a,b){var o=clone(a);if(!b||typeof b!=='object')return o;Object.keys(b).forEach(function(k){var v=b[k];o[k]=(v&&typeof v==='object'&&!Array.isArray(v)&&o[k]&&typeof o[k]==='object')?merge(o[k],v):v});return o}
function session(){try{return w.__sagsGetSession&&w.__sagsGetSession()||{role:w.currentRole||'',profile:w.currentUserProfile||{}}}catch(e){return{role:w.currentRole||'',profile:w.currentUserProfile||{}}}}
function profile(){return session().profile||w.currentUserProfile||{}}
function role(){return U(session().role||profile().role||w.currentRole)}
function safe(v){try{return S(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/[^A-Za-z0-9_.-]+/g,'_').slice(0,80)||'device'}catch(e){return S(v).replace(/[^A-Za-z0-9_.-]+/g,'_').slice(0,80)||'device'}}
function identity(){var s=session(),p=s.profile||{};return safe(p.username||p.userName||p.email||s.username||role()||'device')}
function key(){return 'sagsSettingsV1:'+identity()}
function read(){try{return merge(D,JSON.parse(localStorage.getItem(key())||'{}'))}catch(e){return clone(D)}}
function persist(next,noCloud){P=merge(D,next||P);P.updatedAtMs=Date.now();try{localStorage.setItem(key(),JSON.stringify(P))}catch(e){}apply();render();if(!noCloud)scheduleCloud();return P}
function legalName(){var p=profile();return S(p.name||p.fullName||p.displayName||p.username||p.userName||role()||'Người dùng')}
function shownName(){return S(P.displayName)||legalName()}
function firebaseUid(){var p=profile();try{return S((w.firebase&&w.firebase.auth&&w.firebase.auth().currentUser||{}).uid||p.firebaseUid||p.uid)}catch(e){return S(p.firebaseUid||p.uid)}}
function cloudDoc(){var id=firebaseUid();try{return id&&w.firebase&&w.firebase.firestore?w.firebase.firestore().collection('users').doc(id):null}catch(e){return null}}
function scheduleCloud(){clearTimeout(saveTimer);if(P.autoSync&&navigator.onLine)saveTimer=setTimeout(function(){saveCloud()},650)}
async function saveCloud(){var d=cloudDoc();if(!d){cloudState='Chỉ lưu trên thiết bị';renderStatus();return false}try{await d.set({preferencesV1:Object.assign({},clone(P),{settingsBuild:BUILD})},{merge:true});cloudState='Đã đồng bộ máy chủ';cloudAt=Date.now();renderStatus();return true}catch(e){cloudState='Chờ đồng bộ';renderStatus();return false}}
async function loadCloud(){var d=cloudDoc();if(!d)return;try{var s=await d.get(),r=s.exists&&(s.data()||{}).preferencesV1;if(r&&Number(r.updatedAtMs||0)>Number(P.updatedAtMs||0)){P=merge(D,r);try{localStorage.setItem(key(),JSON.stringify(P))}catch(e){}apply();render()}else if(P.updatedAtMs)await saveCloud();cloudState='Đã đồng bộ máy chủ';cloudAt=Date.now();renderStatus()}catch(e){cloudState='Chờ đồng bộ';renderStatus()}}
function theme(){if(P.appearance==='light'||P.appearance==='dark')return P.appearance;try{return w.matchMedia&&w.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}catch(e){return'dark'}}
function apply(){
 var h=document.documentElement,t=theme();
 h.dataset.sagsAppearance=P.appearance||'dark';h.dataset.sagsFontScale=P.fontScale||'normal';h.dataset.sagsCompact=P.compactMode?'on':'off';h.dataset.sagsSound=P.soundEnabled?'on':'off';h.dataset.sagsVibration=P.vibrationEnabled?'on':'off';
 try{if(typeof w.sagsSetUiTheme==='function')w.sagsSetUiTheme(t);else h.setAttribute('data-ui-theme',t)}catch(e){}
 applyProfile();resetLock()
}
function ensureWelcomeAvatar(){var n=$('v157WelcomeName');if(n&&!$('sagsWelcomeAvatar')){var a=document.createElement('span');a.id='sagsWelcomeAvatar';a.className='sagsWelcomeAvatar';n.parentNode.insertBefore(a,n)}}
function applyProfile(){
 ensureWelcomeAvatar();var n=shownName(),a=S(P.avatarData),initial=(n.match(/[A-ZÀ-Ỹ0-9]/iu)||['U'])[0].toUpperCase(),d=$('v157DrawerAvatar'),wa=$('sagsWelcomeAvatar'),un=$('v157UserName'),g=$('v157WelcomeName');
 function av(el){if(!el)return;var mode=a?'image':'initial',bg=a?'url("'+a.replace(/"/g,'%22')+'")':'',txt=a?'':initial;if(el.dataset.sagsAvatar!==mode)el.dataset.sagsAvatar=mode;if(el.style.backgroundImage!==bg)el.style.backgroundImage=bg;if(el.textContent!==txt)el.textContent=txt;if(el.title!==n)el.title=n}
 av(d);av(wa);
 if(un){un.classList.add('sagsCustomDisplayText');un.dataset.sagsDisplay=n;un.title=n===legalName()?n:n+' · '+legalName()}
 if(g){g.classList.add('sagsCustomGreeting');g.dataset.sagsGreeting='Xin chào, '+n+' 👋'}
}
function patchDeviceFeedback(){
 if(!mediaBase&&w.HTMLMediaElement&&w.HTMLMediaElement.prototype.play){mediaBase=w.HTMLMediaElement.prototype.play;w.HTMLMediaElement.prototype.play=function(){if(read().soundEnabled===false){try{this.pause()}catch(e){}return Promise.resolve()}return mediaBase.apply(this,arguments)}}
 if(!vibrateBase&&navigator.vibrate){try{vibrateBase=navigator.vibrate.bind(navigator);navigator.vibrate=function(p){return read().vibrationEnabled===false?false:vibrateBase(p)}}catch(e){}}
}
function ensureMenu(){
 var body=$('v157MenuBody');if(!body)return;var sections=Array.from(body.querySelectorAll('.v157Section')),sys=sections.find(function(x){return/HỆ THỐNG/i.test(S((x.querySelector('.v157SectionTitle')||{}).textContent))});if(!sys)return;
 if(sys.querySelector('[data-v157-key="settings"],[data-sags-settings-menu]'))return;var b=document.createElement('button');b.type='button';b.className='v157MenuItem';b.dataset.sagsSettingsMenu='1';b.dataset.v157Key='settings';b.innerHTML='<span class="ico">⚙</span><span>Cài đặt</span><span class="meta">Cá nhân · thiết bị · hệ thống</span>';b.onclick=function(){try{w.v157CloseMenu&&w.v157CloseMenu()}catch(e){}open()};var div=sys.querySelector('.v157MenuDivider');div?sys.insertBefore(b,div):sys.appendChild(b)
}
function shell(){
 if($('sagsSettingsCenter'))return;
 var e=document.createElement('div');e.id='sagsSettingsCenter';e.className='sagsSettingsCenter';e.setAttribute('aria-hidden','true');
 e.innerHTML=[
 '<div class="sagsSettingsPanel" role="dialog" aria-modal="true"><header><div><small>E-REPORT SAGS</small><h2>CÀI ĐẶT</h2><p>Cá nhân hóa tài khoản, thiết bị và cách ứng dụng hoạt động.</p></div><button id="sagsSettingsClose">✕</button></header>',
 '<div class="sagsSettingsLayout"><nav class="sagsSettingsNav">',
 '<button data-tab="account">👤 <span>Tài khoản</span></button><button data-tab="appearance">◐ <span>Giao diện</span></button><button data-tab="notify">🔔 <span>Thông báo</span></button><button data-tab="sync">☁ <span>Dữ liệu & đồng bộ</span></button><button data-tab="device">📱 <span>Thiết bị & Offline</span></button><button data-tab="security">🔐 <span>Bảo mật</span></button><button data-tab="update">↻ <span>Cập nhật</span></button><button data-tab="about">ⓘ <span>Thông tin</span></button><button data-tab="diag" id="sagsDiagTab">🛠 <span>Chẩn đoán</span></button>',
 '</nav><main class="sagsSettingsContent">',
 '<section data-page="account"><h3>Tài khoản</h3><p class="desc">Tên hiển thị và avatar chỉ thay giao diện, không đổi tên nghiệp vụ trên roster/biểu mẫu.</p><div class="profile"><div id="sagsAvatarPreview" class="avatar">U</div><div><b id="sagsProfileName">Người dùng</b><span id="sagsProfileMeta">—</span><small id="sagsCloudBadge">Lưu trên thiết bị</small></div></div><div class="grid"><label class="wide">Tên hiển thị<input id="sagsDisplayName" maxlength="48" placeholder="Ví dụ: Đinh Duy Phương"></label><label>Họ tên nghiệp vụ<input id="sagsLegalName" readonly></label><label>Tài khoản<input id="sagsUsername" readonly></label><label>Vai trò<input id="sagsRole" readonly></label><label>Đơn vị<input id="sagsUnit" readonly></label></div><div class="actions"><label class="file">📷 Chọn ảnh<input id="sagsAvatarInput" type="file" accept="image/*"></label><button id="sagsAvatarRemove">Bỏ ảnh</button><button class="primary" id="sagsProfileSave">Lưu hồ sơ hiển thị</button></div></section>',
 '<section data-page="appearance"><h3>Giao diện & trải nghiệm</h3><p class="desc">Áp dụng riêng cho tài khoản này.</p><div class="rows"><label><span><b>Chế độ hiển thị</b><small>Theo hệ thống / Sáng / Tối</small></span><select id="sagsAppearance"><option value="system">Theo hệ thống</option><option value="light">Sáng</option><option value="dark">Tối</option></select></label><label><span><b>Cỡ chữ</b><small>Không đổi chữ trong biểu mẫu PDF</small></span><select id="sagsFont"><option value="small">Nhỏ</option><option value="normal">Tiêu chuẩn</option><option value="large">Lớn</option></select></label><label><span><b>Chế độ gọn trên điện thoại</b><small>Giảm khoảng trống, không ép biểu mẫu</small></span><input id="sagsCompact" class="sw" type="checkbox"></label><label><span><b>Âm thanh thông báo</b></span><input id="sagsSound" class="sw" type="checkbox"></label><label><span><b>Rung phản hồi</b></span><input id="sagsVibration" class="sw" type="checkbox"></label></div></section>',
 '<section data-page="notify"><h3>Thông báo</h3><p class="desc">Cấu hình các nhóm cảnh báo E-REPORT.</p><div class="actions"><button class="primary" id="sagsRequestNotify">🔔 Cho phép thông báo hệ thống</button></div><div class="rows"><label><span><b>Thông báo trên thiết bị</b><small>Công tắc tổng</small></span><input class="sw" data-notify="device" type="checkbox"></label><label><span><b>Chuyến bay mới được phân công</b></span><input class="sw" data-notify="assignment" type="checkbox"></label><label><span><b>Biểu mẫu được bàn giao</b></span><input class="sw" data-notify="handover" type="checkbox"></label><label><span><b>Biểu mẫu bị trả lại / yêu cầu sửa</b></span><input class="sw" data-notify="returned" type="checkbox"></label><label><span><b>Roster thay đổi</b></span><input class="sw" data-notify="roster" type="checkbox"></label><label><span><b>Có phiên bản mới</b></span><input class="sw" data-notify="update" type="checkbox"></label></div></section>',
 '<section data-page="sync"><h3>Dữ liệu & đồng bộ</h3><p class="desc">Theo dõi đúng pipeline nháp 3 lớp của TEST: localStorage → IndexedDB → RTDB Cloud Draft.</p><div class="flow"><div><b>1</b><span>localStorage</span><em id="sagsLocalState">—</em></div><i>→</i><div><b>2</b><span>IndexedDB</span><em id="sagsIdbState">—</em></div><i>→</i><div><b>3</b><span>Cloud Draft</span><em id="sagsCloudDraftState">—</em></div></div><div class="stats"><div><span>Nháp/dữ liệu cục bộ</span><b id="sagsDraftCount">—</b></div><div><span>Cài đặt cloud</span><b id="sagsCloudState">—</b></div><div><span>Lần đồng bộ</span><b id="sagsLastSync">—</b></div><div><span>Dung lượng</span><b id="sagsStorage">—</b></div></div><div class="rows"><label><span><b>Tự đồng bộ khi có Internet</b></span><input id="sagsAutoSync" class="sw" type="checkbox"></label><label><span><b>Cảnh báo khi rời lúc đang Offline có nháp</b></span><input id="sagsWarn" class="sw" type="checkbox"></label></div><div class="actions"><button class="primary" id="sagsSyncNow">☁ Đồng bộ ngay</button><button id="sagsRefreshStatus">Làm mới trạng thái</button></div></section>',
 '<section data-page="device"><h3>Thiết bị & Offline</h3><p class="desc">Tình trạng PWA và khả năng làm việc khi mất mạng.</p><div class="stats"><div><span>Thiết bị</span><b id="sagsDevice">—</b></div><div><span>Mạng</span><b id="sagsNetwork">—</b></div><div><span>PWA</span><b id="sagsPwa">—</b></div><div><span>Service Worker</span><b id="sagsSw">—</b></div><div><span>Cache ứng dụng</span><b id="sagsCaches">—</b></div><div><span>IndexedDB mirror</span><b id="sagsMirror">—</b></div></div><div class="rows"><label class="locked"><span><b>Lưu biểu mẫu Offline</b><small>Luôn bật để bảo vệ dữ liệu nhập dở</small></span><input class="sw" type="checkbox" checked disabled></label></div></section>',
 '<section data-page="security"><h3>Bảo mật</h3><p class="desc">Bảo vệ phiên đăng nhập hiện tại.</p><div class="rows"><label><span><b>Tự khóa khi không thao tác</b><small>Đăng xuất, không xóa nháp</small></span><select id="sagsAutoLock"><option value="0">Tắt</option><option value="5">5 phút</option><option value="15">15 phút</option><option value="30">30 phút</option></select></label><label class="locked"><span><b>Sinh trắc học / PIN</b><small>Chưa hỗ trợ an toàn trên PWA hiện tại</small></span><input class="sw" type="checkbox" disabled></label></div><div class="actions"><button class="primary" id="sagsPassword">🔑 Đổi mật khẩu</button><button disabled>Đăng xuất thiết bị khác · Cần server hỗ trợ</button></div></section>',
 '<section data-page="update"><h3>Cập nhật ứng dụng</h3><p class="desc">Xóa cache giao diện không xóa localStorage hoặc IndexedDB.</p><div class="release"><span>Phiên bản đang chạy</span><b id="sagsRunningVersion">—</b><small id="sagsRunningBuild">—</small></div><div class="note" id="sagsUpdateStatus">Chưa kiểm tra bản mới.</div><div class="actions"><button class="primary" id="sagsCheckUpdate">↻ Kiểm tra cập nhật</button><button id="sagsReload">Tải lại mới nhất</button><button class="danger" id="sagsClearCache">Xóa cache giao diện & tải lại</button></div></section>',
 '<section data-page="about"><h3>Thông tin E-REPORT</h3><div class="actions"><button id="sagsResetDefaults">Khôi phục cài đặt mặc định</button></div><div class="about"><img src="assets/branding/logo.png" alt="SAGS"><div><b>E-REPORT SAGS</b><span id="sagsAboutVersion">—</span><small id="sagsAboutRelease">—</small></div></div><div class="note" id="sagsWhatsNew">Đang đọc ghi chú phiên bản…</div><div class="actions"><button id="sagsCopyVersion">Sao chép thông tin phiên bản</button></div></section>',
 '<section data-page="diag"><h3>Chẩn đoán hệ thống</h3><p class="desc">Chỉ AD thấy mục này; không sao chép mật khẩu hay nội dung biểu mẫu.</p><pre id="sagsDiag">Đang kiểm tra…</pre><div class="actions"><button class="primary" id="sagsRunDiag">Chạy lại</button><button id="sagsCopyDiag">Sao chép chẩn đoán</button></div></section>',
 '</main></div></div>'
 ].join('');
 document.body.appendChild(e);
 $('sagsSettingsClose').onclick=close;e.addEventListener('click',function(x){if(x.target===e)close()});e.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){tab(b.dataset.tab)}});
 bind();tab('account')
}
function tab(k){var c=$('sagsSettingsCenter');if(!c)return;c.querySelectorAll('[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===k)});c.querySelectorAll('[data-page]').forEach(function(p){p.classList.toggle('active',p.dataset.page===k)});if(k==='sync'||k==='device')status();if(k==='update'||k==='about')version(false);if(k==='diag')diagnostics()}
function open(){shell();var c=$('sagsSettingsCenter');if(!c)return false;c.classList.add('show');c.setAttribute('aria-hidden','false');document.body.classList.add('sags-settings-open');try{syncIdentity();render();tab('account');loadCloud()}catch(e){console.error('Settings open failed',e);try{tab('account')}catch(_){}}return true}
function close(){var c=$('sagsSettingsCenter');if(c){c.classList.remove('show');c.setAttribute('aria-hidden','true')}document.body.classList.remove('sags-settings-open')}
w.sagsOpenSettings=open;w.sagsCloseSettings=close;
function bind(){
 $('sagsProfileSave').onclick=function(){persist(Object.assign({},P,{displayName:S($('sagsDisplayName').value)}));toast('Đã lưu tên hiển thị. Tên nghiệp vụ không thay đổi.')};
 $('sagsAvatarInput').onchange=async function(ev){var f=ev.target.files&&ev.target.files[0];if(!f)return;try{var a=await avatar(f);persist(Object.assign({},P,{avatarData:a}));toast('Đã cập nhật ảnh đại diện.')}catch(e){alert('Không đọc được ảnh: '+S(e.message||e))}ev.target.value=''};
 $('sagsAvatarRemove').onclick=function(){persist(Object.assign({},P,{avatarData:''}));toast('Đã bỏ ảnh đại diện.')};
 $('sagsAppearance').onchange=function(e){persist(Object.assign({},P,{appearance:e.target.value}))};$('sagsFont').onchange=function(e){persist(Object.assign({},P,{fontScale:e.target.value}))};$('sagsCompact').onchange=function(e){persist(Object.assign({},P,{compactMode:!!e.target.checked}))};$('sagsSound').onchange=function(e){persist(Object.assign({},P,{soundEnabled:!!e.target.checked}))};$('sagsVibration').onchange=function(e){persist(Object.assign({},P,{vibrationEnabled:!!e.target.checked}))};
 document.querySelectorAll('#sagsSettingsCenter [data-notify]').forEach(function(i){i.onchange=function(){var n=Object.assign({},P.notifications);document.querySelectorAll('#sagsSettingsCenter [data-notify]').forEach(function(x){n[x.dataset.notify]=!!x.checked});persist(Object.assign({},P,{notifications:n}))}});
 $('sagsAutoSync').onchange=function(e){persist(Object.assign({},P,{autoSync:!!e.target.checked}))};$('sagsWarn').onchange=function(e){persist(Object.assign({},P,{warnUnsynced:!!e.target.checked}))};$('sagsAutoLock').onchange=function(e){persist(Object.assign({},P,{autoLockMinutes:Number(e.target.value)||0}))};
 $('sagsSyncNow').onclick=syncNow;$('sagsRefreshStatus').onclick=status;$('sagsCheckUpdate').onclick=function(){version(true)};$('sagsReload').onclick=reload;$('sagsClearCache').onclick=clearCache;$('sagsRunDiag').onclick=diagnostics;$('sagsCopyDiag').onclick=function(){copy(S($('sagsDiag').textContent));toast('Đã sao chép chẩn đoán.')};$('sagsCopyVersion').onclick=function(){copy('E-REPORT SAGS '+runningVersion()+'\nBuild: '+runningBuild());toast('Đã sao chép thông tin phiên bản.')};
 $('sagsPassword').onclick=function(){close();setTimeout(function(){try{if(typeof w.openChangePasswordModal==='function')w.openChangePasswordModal();else $('v157PasswordBtn')&&$('v157PasswordBtn').click()}catch(e){}},80)};$('sagsRequestNotify').onclick=async function(){if(!('Notification' in w)){alert('Thiết bị/trình duyệt này không hỗ trợ thông báo hệ thống.');return}try{var p=await Notification.requestPermission();toast(p==='granted'?'Đã cho phép thông báo hệ thống.':p==='denied'?'Quyền thông báo đang bị chặn.':'Chưa cấp quyền thông báo.')}catch(e){alert('Không thể yêu cầu quyền thông báo: '+S(e.message||e))}};$('sagsResetDefaults').onclick=function(){if(!confirm('Khôi phục toàn bộ cài đặt cá nhân về mặc định? Tên hiển thị và avatar tùy chỉnh cũng sẽ được đặt lại.'))return;persist(clone(D));toast('Đã khôi phục cài đặt mặc định.')}
}
async function avatar(f){if(!/^image\//.test(f.type))throw Error('Tệp không phải hình ảnh.');if(f.size>12*1024*1024)throw Error('Ảnh quá lớn, hãy chọn ảnh dưới 12 MB.');var src=await new Promise(function(ok,bad){var r=new FileReader;r.onload=function(){ok(String(r.result||''))};r.onerror=function(){bad(r.error)};r.readAsDataURL(f)}),im=await new Promise(function(ok,bad){var x=new Image;x.onload=function(){ok(x)};x.onerror=function(){bad(Error('Ảnh không hợp lệ'))};x.src=src}),m=256,sc=Math.min(1,m/Math.max(im.naturalWidth||1,im.naturalHeight||1)),cw=Math.max(1,Math.round(im.naturalWidth*sc)),ch=Math.max(1,Math.round(im.naturalHeight*sc)),c=document.createElement('canvas');c.width=cw;c.height=ch;c.getContext('2d').drawImage(im,0,0,cw,ch);return c.toDataURL('image/jpeg',.78)}
function render(){
 if(!$('sagsSettingsCenter'))return;var p=profile(),n=shownName(),a=S(P.avatarData),pr=$('sagsAvatarPreview');$('sagsDisplayName').value=S(P.displayName);$('sagsLegalName').value=legalName();$('sagsUsername').value=S(p.username||p.userName||session().username||'—');$('sagsRole').value=role()||'—';$('sagsUnit').value=S(p.unit||p.departmentName||p.departmentCode||p.systemDepartment||p.groupCode||'—');$('sagsProfileName').textContent=n;$('sagsProfileMeta').textContent=[role(),S(p.jobTitle||p.position||p.unit||p.departmentName)].filter(Boolean).join(' · ')||'—';if(pr){pr.style.backgroundImage=a?'url("'+a.replace(/"/g,'%22')+'")':'';pr.textContent=a?'':((n.match(/[A-ZÀ-Ỹ0-9]/iu)||['U'])[0].toUpperCase())}
 $('sagsAppearance').value=['system','light','dark'].includes(P.appearance)?P.appearance:'dark';$('sagsFont').value=['small','normal','large'].includes(P.fontScale)?P.fontScale:'normal';$('sagsCompact').checked=!!P.compactMode;$('sagsSound').checked=P.soundEnabled!==false;$('sagsVibration').checked=P.vibrationEnabled!==false;document.querySelectorAll('#sagsSettingsCenter [data-notify]').forEach(function(i){i.checked=P.notifications[i.dataset.notify]!==false});$('sagsAutoSync').checked=!!P.autoSync;$('sagsWarn').checked=!!P.warnUnsynced;$('sagsAutoLock').value=String(Number(P.autoLockMinutes)||0);$('sagsDiagTab').hidden=role()!=='AD';renderStatus()
}
function renderStatus(){if($('sagsCloudBadge'))$('sagsCloudBadge').textContent=cloudState;if($('sagsCloudState'))$('sagsCloudState').textContent=cloudState;if($('sagsLastSync'))$('sagsLastSync').textContent=cloudAt?new Date(cloudAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'—'}
function draftCount(){var n=0;try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i)||'';if(/draft|flight.*session|form.*state|quick.*entry|fsags|roster/i.test(k))n++}}catch(e){}return n}
function bytes(n){if(!n)return'0 B';var u=['B','KB','MB','GB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
async function status(){
 if(!$('sagsLocalState'))return;try{localStorage.setItem('__sags_probe','1');localStorage.removeItem('__sags_probe');$('sagsLocalState').textContent='✓ Sẵn sàng'}catch(e){$('sagsLocalState').textContent='⚠ Không khả dụng'}
 $('sagsIdbState').textContent=w.indexedDB?'✓ Sẵn sàng':'⚠ Không hỗ trợ';var ds=null;try{ds=typeof w.sagsDraftV2Status==='function'?w.sagsDraftV2Status():null}catch(e){};if(!ds)$('sagsCloudDraftState').textContent='Đang nạp Cloud Draft V2';else if(!ds.cloudCapable)$('sagsCloudDraftState').textContent='⚠ RTDB chưa sẵn sàng';else if(!ds.online)$('sagsCloudDraftState').textContent='Offline · chờ mạng';else if(ds.lastCloudError)$('sagsCloudDraftState').textContent='⚠ Chờ đồng bộ RTDB';else if(ds.rosterAssignmentId)$('sagsCloudDraftState').textContent='✓ RTDB sẵn sàng';else $('sagsCloudDraftState').textContent='Chờ mở chuyến được phân công';$('sagsDraftCount').textContent=String(draftCount());if(ds){var draftAt=Math.max(Number(ds.lastCloudSyncAtMs||0),Number(ds.lastPullAtMs||0));if(draftAt>cloudAt)cloudAt=draftAt;}$('sagsDevice').textContent=/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent)?'Điện thoại / Tablet':'Máy tính';$('sagsNetwork').textContent=navigator.onLine?'● Online':'○ Offline';$('sagsPwa').textContent=((w.matchMedia&&w.matchMedia('(display-mode: standalone)').matches)||navigator.standalone)?'Đã cài PWA':'Trình duyệt';$('sagsSw').textContent=navigator.serviceWorker&&navigator.serviceWorker.controller?'Đang hoạt động':'Chưa điều khiển';
 try{var es=await navigator.storage.estimate();$('sagsStorage').textContent=bytes(Number(es.usage||0))+(es.quota?' / '+bytes(Number(es.quota)):'')}catch(e){$('sagsStorage').textContent='—'}
 try{var ks=await caches.keys();$('sagsCaches').textContent=ks.filter(function(x){return/^sags-app-/i.test(x)}).length+' vùng cache'}catch(e){$('sagsCaches').textContent='—'}
 try{var rep=w.sagsIndexedDbFlightStoreV1&&await w.sagsIndexedDbFlightStoreV1.report();$('sagsMirror').textContent=rep&&rep.indexedDb?String(rep.indexedDb.sessions.length)+' chuyến':'Chưa có báo cáo'}catch(e){$('sagsMirror').textContent='Chưa có báo cáo'}renderStatus()
}
async function syncNow(){var b=$('sagsSyncNow');if(b){b.disabled=true;b.textContent='Đang đồng bộ…'}try{if(w.sagsIndexedDbFlightStoreV1)await w.sagsIndexedDbFlightStoreV1.mirrorNow('settings');if(typeof w.sagsDraftV2Pull==='function')await w.sagsDraftV2Pull();if(typeof w.sagsDraftV2Flush==='function')await w.sagsDraftV2Flush();await saveCloud();for(var a of ['sagsV113RestoreMissingMyFlights','sagsV341RepairManualAssignments','dailyRosterRestartMailbox'])try{if(typeof w[a]==='function')await w[a]()}catch(e){}var ds=null;try{ds=typeof w.sagsDraftV2Status==='function'?w.sagsDraftV2Status():null}catch(e){}cloudAt=Math.max(Date.now(),Number(ds?.lastCloudSyncAtMs||0),Number(ds?.lastPullAtMs||0));await status();toast(navigator.onLine?(ds&&ds.cloudCapable?'Đã đồng bộ localStorage → IndexedDB → RTDB.':'Đã đồng bộ các lớp đang sẵn sàng.'):'Đang Offline · nháp vẫn được giữ trên máy và sẽ đẩy RTDB khi có mạng.')}finally{if(b){b.disabled=false;b.textContent='☁ Đồng bộ ngay'}}}
function runningVersion(){return S((document.querySelector('meta[name="sags-release-version"]')||{}).content||'—')}function runningBuild(){return S((document.querySelector('meta[name="sags-release-build"]')||{}).content||'—')}
async function version(show){if($('sagsRunningVersion'))$('sagsRunningVersion').textContent=runningVersion();if($('sagsRunningBuild'))$('sagsRunningBuild').textContent=runningBuild();if($('sagsAboutVersion'))$('sagsAboutVersion').textContent=runningVersion();try{var r=await fetch('./version.json?settings='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);var v=await r.json(),rv=S(v.displayVersion||v.version),newer=rv&&rv!==runningVersion();$('sagsUpdateStatus').textContent=newer?'Có phiên bản mới '+rv+'. Hãy tải lại để cập nhật.':'✓ Bạn đang sử dụng phiên bản mới nhất ('+runningVersion()+').';$('sagsAboutRelease').textContent=[S(v.label),S(v.releasedAt)].filter(Boolean).join(' · ');$('sagsWhatsNew').textContent=S(v.notes||v.message||'Không có ghi chú.');if(show)toast(newer?'Đã phát hiện bản '+rv:'Đây là phiên bản mới nhất.')}catch(e){if($('sagsUpdateStatus'))$('sagsUpdateStatus').textContent=navigator.onLine?'Không kiểm tra được máy chủ lúc này.':'Đang Offline · không thể kiểm tra bản mới.'}}
async function reload(){if(!navigator.onLine){alert('Thiết bị đang Offline. Hãy kết nối mạng trước.');return}try{var r=await navigator.serviceWorker.getRegistration();if(r)await r.update()}catch(e){}location.reload()}
async function clearCache(){if(!navigator.onLine){alert('Không xóa cache khi đang Offline.');return}if(!confirm('Chỉ xóa cache giao diện/service worker. Nháp localStorage và IndexedDB được giữ nguyên. Tiếp tục?'))return;try{var ks=await caches.keys();await Promise.all(ks.filter(function(k){return/^sags-app-(shell|meta)-/i.test(k)}).map(function(k){return caches.delete(k)}));location.reload()}catch(e){alert('Không xóa được cache: '+S(e.message||e))}}
async function diagnostics(){if(!$('sagsDiag'))return;if(role()!=='AD'){$('sagsDiag').textContent='Chẩn đoán nâng cao chỉ dành cho AD.';return}var ds=null;try{ds=typeof w.sagsDraftV2Status==='function'?w.sagsDraftV2Status():null}catch(e){}var a=['E-REPORT SAGS · SETTINGS DIAGNOSTICS','Time: '+new Date().toISOString(),'Version: '+runningVersion(),'Build: '+runningBuild(),'Role: '+role(),'Online: '+navigator.onLine,'Service Worker: '+!!(navigator.serviceWorker&&navigator.serviceWorker.controller),'IndexedDB: '+!!w.indexedDB,'Cloud settings: '+cloudState,'Cloud Draft V2: '+(ds?JSON.stringify({cloudCapable:ds.cloudCapable,online:ds.online,hasAssignment:!!ds.rosterAssignmentId,lastCloudSyncAtMs:ds.lastCloudSyncAtMs,lastPullAtMs:ds.lastPullAtMs,lastCloudError:ds.lastCloudError,cloudWrites:ds.cloudWrites,idbWrites:ds.idbWrites}):'not-ready'),'Local draft-like keys: '+draftCount()];try{var ks=await caches.keys();a.push('Caches: '+ks.filter(function(x){return/^sags-app-/i.test(x)}).join(', '))}catch(e){}$('sagsDiag').textContent=a.join('\n')}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch(e){var x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();try{document.execCommand('copy')}catch(z){}x.remove()}}
function toast(t){var e=document.createElement('div');e.className='sagsSettingsToast';e.textContent=t;document.body.appendChild(e);setTimeout(function(){e.classList.add('show')},20);setTimeout(function(){e.classList.remove('show');setTimeout(function(){e.remove()},250)},2200)}
function resetLock(){clearTimeout(lockTimer);var m=Number(P.autoLockMinutes)||0;if(!m||!document.body.classList.contains('v157-authenticated'))return;lockTimer=setTimeout(function(){try{close();if(typeof w.roleLogout==='function')w.roleLogout();else if($('v157LogoutBtn'))$('v157LogoutBtn').click()}catch(e){}},m*60000)}
function syncIdentity(){var i=identity();if(i===uidKey)return;uidKey=i;P=read();cloudState='Chỉ lưu trên thiết bị';cloudAt=0;apply();render();if(i!=='device')setTimeout(loadCloud,250)}
function beforeLeave(e){if(P.warnUnsynced&&navigator.onLine===false&&draftCount()){e.preventDefault();e.returnValue=''}}
function refreshSettingsIdentity(){syncIdentity();ensureMenu();applyProfile()}
function observeSettingsMenu(){var body=$('v157MenuBody');if(!body)return;try{observer&&observer.disconnect()}catch(_){}observer=new MutationObserver(function(){requestAnimationFrame(function(){ensureMenu()})});observer.observe(body,{childList:true,subtree:true})}
function install(){shell();syncIdentity();patchDeviceFeedback();ensureMenu();observeSettingsMenu();if(!w.__SAGS_SETTINGS_CLICK_DELEGATE__){w.__SAGS_SETTINGS_CLICK_DELEGATE__=true;document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('[data-v157-key="settings"],[data-sags-settings-menu]');if(!b)return;e.preventDefault();e.stopPropagation();document.body.classList.remove('v157-drawer-open');open()},{capture:true})}['pointerdown','keydown','touchstart'].forEach(function(ev){document.addEventListener(ev,resetLock,{passive:true,capture:true})});addEventListener('online',function(){status();if(P.autoSync)syncNow()},{passive:true});addEventListener('offline',status,{passive:true});addEventListener('beforeunload',beforeLeave);['sags:login','sags:logout','sags:rolechange','sags:profilechange','sags:ui-ready'].forEach(function(name){w.addEventListener(name,function(){setTimeout(function(){refreshSettingsIdentity();observeSettingsMenu()},0)},{passive:true})});w.addEventListener('pageshow',function(){refreshSettingsIdentity();observeSettingsMenu()},{passive:true});document.addEventListener('visibilitychange',function(){if(!document.hidden){refreshSettingsIdentity();observeSettingsMenu()}},{passive:true});try{w.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',function(){if(P.appearance==='system')apply()})}catch(e){}} 
w.sagsNotificationAllowed=function(k){var n=read().notifications||{};return n.device!==false&&n[S(k)]!==false};w.sagsVibrate=function(p){if(read().vibrationEnabled===false)return false;try{return vibrateBase?vibrateBase(p):(navigator.vibrate&&navigator.vibrate(p))||false}catch(e){return false}};w.sagsGetSettings=function(){return clone(read())};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install()
})(window);
