const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),css=fs.readFileSync(path.join(root,'app/styles/fixed-ui-rule-v64113.css'),'utf8');
const at=css.indexOf('V6.4.144 · UNIFIED OPERATIONAL CONTROLS');
assert(at>=0,'unified operational control layer missing');
const block=css.slice(at);
assert(block.includes('#sagsWorkDatePicker{\n  display:none!important'),'fake My Flight date picker button must be removed');
assert(block.includes(':is(.m101Calendar,.m101Down,#m101DateText)'),'pixel My Flight decorative date layers must be removed');
assert(block.includes('content:"GIỜ"!important'),'Quick Time helper must be a flat GIỜ label');
assert(block.includes('.quickTimeNow::after{\n  content:none!important'),'legacy inner clock drawing must be removed');
assert(block.includes('grid-template-columns:minmax(0,1fr) 42px!important'),'Quick Time must use one integrated field + trailing action');
assert(block.includes('input:not([type="checkbox"]):not([type="radio"]):not([type="file"]):not(.quickTimeInput):not(.ffInput):not(.v462TestControl)'),'paper/final/runtime entry fields must be excluded from generic UI controls');
assert(css.includes('FSAGS54/94 TECHNICAL HITBOX GUARD'),'FSAGS54/94 hitbox protection must remain');
console.log('V6.4.144 unified operational control guard passed.');
