const fs=require('fs'),path=require('path'),acorn=require('acorn'),terser=require('terser');
const root=path.resolve(__dirname,'..'),out=path.join(root,'app/generated');const phases=['archive','tools','flight','control','postcontrol','performance'];
const check=process.argv.includes('--check');function emit(p,s){if(check){if(!fs.existsSync(p)||fs.readFileSync(p,'utf8')!==s)throw Error('Generated asset out of date: '+path.relative(root,p));return;}fs.writeFileSync(p,s)}
const read=p=>fs.readFileSync(path.join(root,p),'utf8');const write=(name,s)=>emit(path.join(out,name),s+'\n');
function walk(n,fn){if(!n||typeof n!=='object')return;if(fn(n)===false)return;for(const v of Object.values(n))if(Array.isArray(v))v.forEach(x=>walk(x,fn));else if(v&&typeof v==='object')walk(v,fn)}
async function main(){fs.mkdirSync(out,{recursive:true});const src=read('app/core/app.v503.js'),ast=acorn.parse(src,{ecmaVersion:'latest'}),compiled={};
 for(const phase of phases){const edits=[];walk(ast,n=>{const match=x=>x?.type==='Identifier'&&x.name==='phase'||x&&src.slice(x.start,x.end).includes('document.currentScript')&&src.slice(x.start,x.end).includes('phase');if(n.type==='BinaryExpression'&&['===','!==','==','!='].includes(n.operator)&&match(n.left)&&n.right.type==='Literal'&&typeof n.right.value==='string'){const eq=phase===n.right.value;edits.push([n.start,n.end,String(n.operator.includes('!')?!eq:eq)]);return false}});let s=src;for(const [a,b,v]of edits.sort((a,b)=>b[0]-a[0]))s=s.slice(0,a)+v+s.slice(b);compiled[phase]=(await terser.minify(s,{compress:{passes:2,sequences:false},mangle:false,format:{comments:false}})).code;}
 const occurrences=new Map();for(const phase of phases){const s=compiled[phase];for(const n of acorn.parse(s,{ecmaVersion:'latest'}).body){const code=s.slice(n.start,n.end);if(n.type!=='ExpressionStatement'||code.length<1500)continue;const list=occurrences.get(code)||[];list.push(phase);occurrences.set(code,list)}}
 const common=[...occurrences].filter(([,p])=>p.length===phases.length).map(([s])=>s),lookup=new Map(common.map((s,i)=>[s,i]));write('core-shared.js','/* Shared code is parsed once; calls retain original phase order and currentScript. */\nwindow.sagsCoreSharedRuns=['+common.map(s=>'function(){'+s+'}').join(',')+'];');
 for(const phase of phases){const s=compiled[phase],parts=acorn.parse(s,{ecmaVersion:'latest'}).body.map(n=>{const code=s.slice(n.start,n.end);return lookup.has(code)?'window.sagsCoreSharedRuns['+lookup.get(code)+']();':code});write('core-'+phase+'.js',parts.join('\n'));}
 const runtime=read('app/core/runtime.v503hf2.bundle.js'),body=acorn.parse(runtime,{ecmaVersion:'latest'}).body;let chunks=[],current='';for(const n of body){const code=runtime.slice(n.start,n.end)+'\n';if(current&&Buffer.byteLength(current)+Buffer.byteLength(code)>140000){chunks.push(current);current=''}current+=code}if(current)chunks.push(current);chunks.forEach((s,i)=>write('runtime-'+(i+1)+'.js',s));
 // Keep source order; combine only expression-only scripts without currentScript or strict directives.
 let html=read('index.html'),build=JSON.parse(read('version.json')).build;html=html.replace(/<script\b[^>]*src=["']\.\/app\/(?:core\/app\.v503\.js|generated\/core-[^"'?]+)[^"']*["'][^>]*data-phase=["']([^"']+)["'][^>]*><\/script>/g,(tag,phase)=>'<script src="./app/generated/core-'+phase+'.js?v='+build+'" data-phase="'+phase+'"></script>');
 if(!html.includes('./app/generated/core-shared.js'))html=html.replace('<script src="./app/generated/core-archive.js','<script src="./app/generated/core-shared.js?v='+build+'"></script>\n<script src="./app/generated/core-archive.js');
 const runtimeTags=chunks.map((_,i)=>'<script src="./app/generated/runtime-'+(i+1)+'.js?v='+build+'"></script>').join('\n');html=html.replace(/<script\b[^>]*src=["']\.\/app\/core\/runtime\.v503hf2\.bundle\.js[^"']*["'][^>]*><\/script>|(?:<script src="\.\/app\/generated\/runtime-\d+\.js[^"']*"><\/script>\s*)+/g,runtimeTags+'\n');
 html=html.replace(/<script type="module" src="\.\/app\/modules\/ai\.js[^"']*"><\/script>/,'<script src="./app/modules/feature-loader.v1.js?v='+build+'"></script>');const groupFile=path.join(out,'boot-groups.json');let groups=fs.existsSync(groupFile)?JSON.parse(fs.readFileSync(groupFile)):[];
 for(let i=0;i<groups.length;i++)write('boot-group-'+(i+1)+'.js',groups[i].map(p=>'/* '+p+' */\n'+read(p)).join('\n;\n'));
 const re=/<script\b[^>]*src="(\.\/app\/boot\/[^"?]+)\?[^"]*"><\/script>/g,entries=[...html.matchAll(re)];let pending=[];const replacements=[];
 const flush=()=>{if(pending.length>1){const files=pending.map(m=>m[1]),index=groups.push(files);write('boot-group-'+index+'.js',files.map(p=>'/* '+p+' */\n'+read(p)).join('\n;\n'));replacements.push([pending[0].index,pending.at(-1).index+pending.at(-1)[0].length,pending.map(m=>m[0].replace(/\s+src="[^"]*"/,'')).join('\n')+'\n<script src="./app/generated/boot-group-'+index+'.js?v='+build+'"></script>']);}pending=[];};
 for(const m of entries){const code=read(m[1]);const body=acorn.parse(code,{ecmaVersion:'latest'}).body,safe=body.every(n=>n.type==='ExpressionStatement'&&!n.directive)&&!code.includes('document.currentScript');if(!safe){flush();continue}if(pending.length&&html.slice(pending.at(-1).index+pending.at(-1)[0].length,m.index).trim())flush();pending.push(m);}flush();for(const [a,b,v]of replacements.sort((a,b)=>b[0]-a[0]))html=html.slice(0,a)+v+html.slice(b);emit(groupFile,JSON.stringify(groups,null,2)+'\n');
 emit(path.join(root,'index.html'),html);
 const meta=JSON.parse(read('asset-manifest.json'));for(const name of fs.readdirSync(out))meta.assets['./app/generated/'+name]={};meta.assets['./app/modules/feature-loader.v1.js']={};meta.assets['./app/modules/firebase-read-coalescer.v1.js']={};
 // Source monoliths remain reviewable in Git, but are not executable-cache assets.
 for(const group of groups)for(const p of group)delete meta.assets[p];delete meta.assets['./app/core/app.v503.js'];delete meta.assets['./app/core/runtime.v503hf2.bundle.js'];
 const scripts=[...html.matchAll(/<script\b[^>]*src=["'](\.\/[^"'?]+)[^"']*["'][^>]*>/g)].map(m=>m[1]);let sw=read('service-worker.js');const extra=['./app/styles/aviation-reference.v1.css','./assets/branding/apron-night-v6494.webp','./app/styles/app.bundle.css','./app/styles/new-ui-v1.css',...Object.keys(meta.assets).filter(p=>p.startsWith('./app/styles/boot-')),'./service-worker.js','./version.json','./data/airline-form-catalog.json','./app/modules/stability.v6-core.js','./app/modules/mobile-draft-recovery.v1.js','./app/modules/indexeddb-flight-store.v1.js'];sw=sw.replace(/const SAGS_BOOTSTRAP=\[[^\n]*\];/, 'const SAGS_BOOTSTRAP='+JSON.stringify([...new Set(['./index.html',...scripts.filter(p=>!p.includes('/ai.js')&&!p.includes('/carrier-notebook.')), ...extra])])+';');sw=sw.replace("const runtimeOk=text.includes('runtime.v503hf2.bundle.js?v='+BUILD);","const runtimeOk=text.includes('app/generated/runtime-1.js?v='+BUILD);");emit(path.join(root,'service-worker.js'),sw);
 for(const [name]of Object.entries(meta.assets)){const bytes=fs.readFileSync(path.join(root,name));meta.assets[name]={sha256:require('crypto').createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};}fs.writeFileSync(path.join(root,'asset-manifest.json'),JSON.stringify(meta,null,2)+'\n');
 console.log(JSON.stringify({phases:phases.length,sharedBodies:common.length,runtimeChunks:chunks.length,generatedBytes:fs.readdirSync(out).reduce((n,f)=>n+fs.statSync(path.join(out,f)).size,0)}));
}
main().catch(e=>{console.error(e);process.exitCode=1});
